### ISSUE TITLE
Option to hide unmodified (!) Mysterys from map view

### ISSUE THREAD

**Issue by dcjkfgdjhd** [cgeo/cgeo#10429]
## What function are you missing

I would like there to be a filter in the map view to hide all mystery caches that do NOT have modified coordinates. The reason being that unsolved mysteries are not located where their coordinates say anyway, so they clutter up the map unnecessarily.

Mysteries with modified coordinates have essentially been turned into traditionals, and the icon really shows where they are, so they should still be displayed on the map.

**Comment by jakedot** [comment]
I don't think that such a filter would be all that useful, it would probably only work for caches you saved already, and for those you can filter by "has modified coordinates" already.

Also consider that in some cases, caches can actually have modified coordinates without c:geo being able to detect that correctly, e.g. when you have imported caches with modified coordinates from a GPX, where there is no flag for it.

**Comment by dcjkfgdjhd** [comment]
Hmm not sure how cgeo loads the caches into the map view. But the map view on GC.com displays modified caches moved to the new place and even with a different icon, as they "are not considered mysteries anymore now they are solved". Can cgeo not access that somehow?

I agree with you about mysteries imported from GPX or saved locally by the user: clearly, for those the user made a conscious choice that he wants to see them, so they should be displayed.

I only talk about hiding silly unsolved mystery fake coordinates cluttering up the map view in cases where there is no reason to assume the user cares about them.

**Comment by eddiemuc** [comment]
PR #10913 adds a filter for changed coords

**Comment by jakedot** [comment]
I have successfully used the filter system to implement this use case (I filtered cache types for those which typically have no corrected coordinates, and added the "has corrected coordinates" filter with the "use or instead of and" option).

However, this doesn't enable you to use additional filters concurrently to narrow the result set (you can't mix or / and combination).

I proposed to add a filter that allows you to add a saved filter as a building block to other filters, I believe you or someone else did too. 

This would enable to save the "corrected coords or type which is like traditional" filter and use it together with other filters.

**Comment by eddiemuc** [comment]
> I have successfully used the filter system to implement this use case (I filtered cache types for those which typically have no corrected coordinates, and added the "has corrected coordinates" filter with the "use or instead of and" option).

Have you installed the PR above directly for this? Because at least I did not merge "filtering for changed coords" into master

> I proposed to add a filter that allows you to add a saved filter as a building block to other filters, I believe you or someone else did too. 

Yes there's an issue for this on my list, and this will be implemented. Have to ask for a little patience though, there's just so much work to do in this whole topic...

But if I understand you correctly, the current implementation does not really solve your request in an easy way (without cresting complex filters). Have to think about this...

**Comment by dcjkfgdjhd** [comment]
Wouldn't the easiest approach be to "split" the cache type "mystery" into two cachetypes "mystery (unsolved)" and "mystery (solved)" everywhere in the app? That would make filtering easy (just filter out "(unsolved)"), it would allow using different icons for the two types just like on the GC website, and it would be very easy to understand for users, unlike complex filtering.

**Comment by eddiemuc** [comment]
> Wouldn't the easiest approach be to "split" the cache type "mystery" into two cachetypes "mystery (unsolved)" and "mystery (solved)" everywhere in the app? 

Hm this implies that every user of c:geo has the same understanding of "unsolved" vs "solved". Meaning that every user understands that "solved" is equivalent to "had corrected coordinates"

I don't use "corrected coordinates" for unsolved mysteries myself, so I would be out myself from this definition. Also, not all Geocaching platforms support coordinate correction, what about those?

**Comment by eddiemuc** [comment]
My current idea: adding a checkbox "exclude mysteries with unchanged coordinates" to the list of "exclude" options (exclude active, exclude disabled, exclude archived). What do you think?

Note that this option will consequently also exclude mysteries from opencaching etc since they don't have the concept of changed coordinates

**Comment by murggel** [comment]
> My current idea: adding a checkbox "exclude mysteries with unchanged coordinates" to the list of "exclude" options (exclude active, exclude disabled, exclude archived). What do you think?
> 
> Note that this option will consequently also exclude mysteries from opencaching etc since they don't have the concept of changed coordinates

How about "exclude solved mysteries" and defining solved mysteries "has changed coordinates or has final waypoint with valid coordinates". Don't know, how users mostly set their solved coordinates..

**Comment by eddiemuc** [comment]
> How about "exclude solved mysteries" and defining solved mysteries "has changed coordinates or has final waypoint with valid coordinates".

Assuming you mean "exclude unsolved mysteries" (?) I like this idea

**Comment by jakedot** [comment]
> Have you installed the PR above directly for this? Because at least I did not merge "filtering for changed coords" into master

Oops, turns out I just abused the "has user note" which I generally only use for storing solved cache solutions / coordinates. But doesn't matter, the use case is the same, just with the other filter.


>> How about "exclude solved mysteries" and defining solved mysteries "has changed coordinates or has final waypoint with valid coordinates".

> Assuming you mean "exclude unsolved mysteries" (?) I like this idea

Could this be implemented as a predefined "stored filter"?

Either way would be fine for me.

**Comment by murggel** [comment]
> > How about "exclude solved mysteries" and defining solved mysteries "has changed coordinates or has final waypoint with valid coordinates".
> 
> Assuming you mean "exclude unsolved mysteries" (?) I like this idea

Sure, was a typo

**Comment by fm-sys** [comment]
Should we really add this to the quick settings pop-up? There are many other filters which probably have at least the same priority. I think it's enough to have this filter only inside the filter framework...

**Comment by eddiemuc** [comment]
> Should we really add this to the quick settings pop-up? There are many other filters which probably have at least the same priority. I think it's enough to have this filter only inside the filter framework... 

No, not there. I am solely talking about the status filter in the new filter framework

**Comment by fm-sys** [comment]
OK, sorry. Didn't have followed the discussion completely...

**Comment by dcjkfgdjhd** [comment]
> 
> 
> > Wouldn't the easiest approach be to "split" the cache type "mystery" into two cachetypes "mystery (unsolved)" and "mystery (solved)" everywhere in the app?
> 
> Hm this implies that every user of c:geo has the same understanding of "unsolved" vs "solved". Meaning that every user understands that "solved" is equivalent to "had corrected coordinates"
> 
> I don't use "corrected coordinates" for unsolved mysteries myself, so I would be out myself from this definition. Also, not all Geocaching platforms support coordinate correction, what about those?

Obviously the exact wording could be adapted. Maybe just "mystery" vs. "mystery (updated coordinate)". I think it really makes sense to think of them as a separate cache type, because by updating the coordinate they have effectively become tradis/multis, and will be handled by users quite differently as a result of that.

(Anyway, the idea to have a different icon for mysteries with updated coordinates would make sense independently of this, just like on the GC.com map.)

**Comment by jakedot** [comment]
> I think it really makes sense to think of them as a separate cache type, because by updating the coordinate they have effectively become tradis/multis, and will be handled by users quite differently as a result of that.

It really doesn't,  because while it may be true for pure "mystery" Unknown Caches (which is the official cache type) there are some which really function more like multis and need you to visit e.g. the header coordinates and multiple stages before you can actually open the container at the finals (if you can even calculate the finals at home). For example I had a mystery which required you to translate Hebrew text, find an advertisement sticker with Hebrew on it and then use the advertised phone number to calculate the final coordinates.

> Anyway, the idea to have a different icon for mysteries with updated coordinates would make sense independently of this, just like on the GC.com map.

The official app doesn't actually change the cachetype or the cache icon. They do essentially the same thing we do (if we know the cache listing actually has corrected coordinates): display an overlay over the actual cache icon. We use the red flag symbol, and they use the puzzle part. They just overlay it over the whole icon, which we don't since we display more than one info overlay if e.g. it's also been found/owned/offline log etc.

I see no real reason to change that, maybe we could make it configurable to display the puzzle part like the big blue "DNF" icon, which already is configurable.

**Comment by fm-sys** [comment]
> maybe we could make it configurable to display the puzzle part like the big blue "DNF" icon, which already is configurable.

We should not add another preference, but we could reuse the "big icon" setting for the "puzzle" icon as well

**Comment by dcjkfgdjhd** [comment]
>there are some which really function more like multis and need you to visit e.g. the header coordinates 
>and multiple stages before you can actually open the container at the finals

That is exactly what I wrote. They either get turned into tradis *or* into multis. But in *both* cases have they been changed into another de facto cache type; one where the coordinates are no longer meaningless but now meaningful, so that you would interact with a cache marker of such a cache very differently than before (e.g. by adding them to a planned tour, which would never make sense for an unsolved mystery).
 
> The official app doesn't actually change the cachetype or the cache icon. 

I have no idea what the useless official app does, but the maps on GC.com definitely do that. The question mark icon gets replaced by a puzzle tile icon, even in a different color (!).

**Comment by dcjkfgdjhd** [comment]
> I see no real reason to change that, maybe we could make it configurable to display the puzzle part like the big blue "DNF" icon, which already is configurable.

That is essentially what I proposed.

**Comment by jakedot** [comment]
> We should not add another preference, but we could reuse the "big icon" setting for the "puzzle" icon as well

probably a good idea. While we're at it, should the "owner" star icon be embiggened as well? See Screenshot.

> That is exactly what I wrote. They either get turned into tradis _or_ into multis. But in _both_ cases have they been changed into another de facto cache type; one where the coordinates are no longer meaningless but now meaningful,

well there are some limited number of mysterys which have meaningful coordinates at the header, think field puzzles, or multis which have "do at home" mystery elements later on. But whatever, the workaround for those to also be included in the proposed filter would be to set the header coordinates as finals temporarily, not too unreasonable.

>so that you would interact with a cache marker of such a cache very differently than before (e.g. by adding them to a planned tour, which would never make sense for an unsolved mystery).

> That is essentially what I proposed.

But basically, this would only affect the map, not displaying of the cache type icons elsewhere, would it? That's what I was trying to get to.

Sorry if I made a comment which was a bit meaningless/confusing.

**Comment by dcjkfgdjhd** [comment]
> well there are some limited number of mysterys which have meaningful coordinates at the header, think field puzzles, or multis which have "do at home" mystery elements later on. 

True, but those are really rare.

>But whatever, the workaround for those to also be included in the proposed filter would be to set the header coordinates as finals temporarily, not too unreasonable.

Agreed.

> But basically, this would only affect the map, not displaying of the cache type icons elsewhere, would it? That's what I was trying to get to.

Yes, my initial proposal was purely about the map. Just meaningless mystery icons cluttering up the map on a small phone screen with never-enough screen real estate.

I have no strong preference on how the icon is displayed elsewhere.

**Comment by eddiemuc** [comment]
Hi @dcjkfgdjhd , @jakedot, thanks for the really good discussion you had on the topic of "solved mystery" handling. I see several potential feature requests in this discussion e.g. potentially adding a new cache type to c:geo, changing the marker logic for map mystery display etc. (I might now have read the whole discussion carefully enough, maybe there is even more in it).

To solve the original topic I am currently working on a "solved/unsolved mystery" filter option as proposed by @murggel further above. Had some great input yesterday wrt GUI design for this too :-) You may want to watch PR #10913 for this.

The other things discussed would go beyond the topic of this issue imho.  Would you be so kind as to open new issues for the different requested features?

**Comment by dcjkfgdjhd** [comment]
Thanks a lot for working on this! I created #10924 to propose the icon change.
