### ISSUE TITLE
Cache details menu unreadable (device specific)

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#10487]
## Bug description 

Two users report, that the cache details menu is unreadable with light skin.
I can not reproduce this problem although I have nearly the same device (Samsung S20+ vs S20). 

### Steps to reproduce the problem

- Open cache
- Click on three-dot button

### Actual result after these steps 

![grafik](https://user-images.githubusercontent.com/949669/116202245-a601a700-a73a-11eb-855e-c7050bcc0853.png)

### Expected result after these steps 

On my device it shows the black menu, which is IMHO OK

## c:geo version 

2021.04.25

## Reproducible 

Yes, for that user

## System information 

```
--- System information ---
c:geo version: 2021.04.25

Device:
-------
- Device type: SM-G986B (y2sxeea, samsung)
- Available processors: 8
- Android version: 11
- Android build: RP1A.200720.012.G986BXXS7DUC9
- Sailfish OS detected: false
- Google Play services: enabled - 21.12.13 (150400-367530751)
- HW acceleration: disabled (manually changed)

Sensor and location:
-------
- Low power mode: inactive
- Compass capabilities: yes
- Rotation vector sensor: present
- Orientation sensor: present
- Magnetometer & Accelerometer sensor: present
- Direction sensor used: rotation vector

Program settings:
-------
- Hide caches: -
- Hide waypoints: -
- Set language: de
- System date format: dd.MM.yy
- Debug mode active: no
- Live map mode: true
- OSM multi-threading: true / threads: 4
- Global filter: display all caches
- Last backup: never
- Routing mode: Walk
- Map: OpenStreetMap.de
- Id: cgeo.geocaching.maps.mapsforge.MapsforgeMapProvider$OsmdeMapSource
- Atts: OpenStreetMap DE, map data OpenStreetMap contributors
- Theme: none

Services:
-------
- Geocaching sites enabled:
geocaching.com: Logged in (Anmeldung OK) / PREMIUM
- Geocaching.com date format: dd/MM/yyyy
- BRouter installed: false / connection available: false
- Installed c:geo plugins: none

Permissions & paths:
-------
- Fine location permission: granted
- Write external storage permission: granted
- System internal c:geo dir: /data/user/0/cgeo.geocaching (76,2 GB free) v2 internal isDir(7 entries)
- Legacy User storage c:geo dir: /storage/emulated/0/cgeo (76,2 GB free) v2 external non-removable isDir(6 entries)
- Geocache data: /storage/emulated/0/Android/data/cgeo.geocaching/files/GeocacheData (76,2 GB free) v2 external non-removable isDir(28 entries)
- Internal theme sync (is turned ON): /data/user/0/cgeo.geocaching/MapThemeData (76,2 GB free) v2 internal isDir(0 entries)
- Public Folders: #9
- BASE: /cgeo (User-Defined)[/cgeo[DOCUMENT#0:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo, Av:true, files:>=1, dirs:>=9, totalFileSize:>=609,5 KB, free space: 76,2 GB, files on device: 13511675)
- OFFLINE_MAPS: /cgeo/maps (Default)[/cgeo/maps[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/maps]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Fmaps, Av:true, files:10, dirs:1, totalFileSize:3,2 GB, free space: 76,2 GB, files on device: 13511675)
- OFFLINE_MAP_THEMES: /cgeo/maps/_themes (Default)[/cgeo/maps/_themes[PERSISTABLE_FOLDER(OFFLINE_MAPS)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/maps/_themes]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Fmaps%2F_themes, Av:true, files:0, dirs:0, totalFileSize:0 B, free space: 76,2 GB, files on device: 13511675)
- LOGFILES: /cgeo/logfiles (Default)[/cgeo/logfiles[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/logfiles]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Flogfiles, Av:true, files:1, dirs:0, totalFileSize:609,5 KB, free space: 76,2 GB, files on device: 13511675)
- GPX: /cgeo/gpx (User-Defined)[/cgeo/gpx[DOCUMENT#0:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo%2Fgpx::]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo%2Fgpx/document/primary%3Acgeo%2Fgpx, Av:true, files:0, dirs:0, totalFileSize:0 B, free space: 76,2 GB, files on device: 13511675)
- BACKUP: /cgeo/backup (Default)[/cgeo/backup[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/backup]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Fbackup, Av:true, files:0, dirs:0, totalFileSize:0 B, free space: 76,2 GB, files on device: 13511675)
- FIELD_NOTES: /cgeo/field-notes (Default)[/cgeo/field-notes[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/field-notes]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Ffield-notes, Av:true, files:7, dirs:0, totalFileSize:2,2 KB, free space: 76,2 GB, files on device: 13511675)
- SPOILER_IMAGES: /cgeo/GeocachePhotos (Default)[/cgeo/GeocachePhotos[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/GeocachePhotos]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2FGeocachePhotos, Av:true, files:0, dirs:3, totalFileSize:0 B, free space: 76,2 GB, files on device: 13511675)
- TEST_FOLDER: [Legacy]/data/user/0/cgeo.geocaching/files/unittest (Default)[/data/user/0/cgeo.geocaching/files/unittest[FILE#1:p-file:///data/user/0/cgeo.geocaching/files::/unittest]] (Uri: file:///data/user/0/cgeo.geocaching/files/unittest, Av:true, files:0, dirs:0, totalFileSize:0 B, free space: 76,2 GB, files on device: -1)
- Map render theme path:
- PersistedDocumentUris: #1
- TRACK: null
- Persisted Uri Permissions: #2
- content://com.android.externalstorage.documents/tree/primary%3Acgeo (27. März, 13:44):RW
- content://com.android.externalstorage.documents/tree/primary%3Acgeo%2Fgpx (2. Apr., 19:33):RW
- Database: /data/user/0/cgeo.geocaching/databases/data (v94, Size:1,3 MB) on system internal storage
-Settings: v5, Count:120
--- End of system information ---
```

## Screenshots 

see above

**Comment by rsudev** [comment]
Even your screenshot shows the original problem: The text colour is taken from the theme (black), and the menu background from some device-global UI setting (probably a dark theme). In your context it is still somewhat readable, but if the device theme is a bit darker, this will be a real issue. (But how this comes in this context I have no real clue up front...)
Do you have an idea with which version it may have started to look like this (on your device)?

**Comment by Lineflyer** [comment]
My device (Samsung S20, Android11) is OK, although I  am even using a system wide dark theme.
The user is using a system wide light theme (I explicitly asked that and you can also see it from the screenshot looking at the softkey bar at the bottom) on his Samsung S20+, Android 11.
Not sure why it is not OK on that device while its OK on mine.

AFAIR we had this issue before...

**Comment by fm-sys** [comment]
I've had a similar problem some time ago. But when trying to reproduce it was gone. Does the problem occur permanently for the user?

**Comment by Lineflyer** [comment]
Not sure...will ask to reboot, just to make sure.

**Comment by Lineflyer** [comment]
Second user, same problem.
This time it is a Samsung Note20, the other was a S20+. Both Android 11

Affected menus are for both users:
- Menu in cache details (behind three-dot icon)
- Navigation menu in cache-details (behind Arrow with dot icon)
- Everything else, seems OK

Second user system information:
```
--- System information ---
c:geo version: 2021.04.25

Device:
-------
- Device type: SM-N986B (c2sxeea, samsung)
- Available processors: 8
- Android version: 11
- Android build: RP1A.200720.012.N986BXXS1DUD1
- Sailfish OS detected: false
- Google Play services: enabled - 21.12.13 (150400-367530751)
- HW acceleration: disabled (manually changed)

Sensor and location:
-------
- Low power mode: inactive
- Compass capabilities: yes
- Rotation vector sensor: present
- Orientation sensor: present
- Magnetometer & Accelerometer sensor: present
- Direction sensor used: rotation vector

Program settings:
-------
- Hide caches: own/found disabled archived
- Hide waypoints: visited
- Set language: de_DE (system default)
- System date format: dd.MM.yy
- Debug mode active: no
- Live map mode: true
- OSM multi-threading: false / threads: 1
- Global filter: display all caches
- Last backup: never
- Routing mode: Bike
- Map: Baden-wuerttemberg (Offline)
- Id: cgeo.geocaching.maps.mapsforge.MapsforgeMapProvider$OfflineMapSource:primary:cgeo/maps/baden-wuerttemberg.map
- Atts: Map data (c) OpenStreetMap contributors
- Theme: none

Services:
-------
- Geocaching sites enabled:
geocaching.com: Logged in (Anmeldung OK) / PREMIUM
- Geocaching.com date format: dd.MM.yyyy
- BRouter installed: true / connection available: false
- Installed c:geo plugins: none

Permissions & paths:
-------
- Fine location permission: granted
- Write external storage permission: granted
- System internal c:geo dir: /data/user/0/cgeo.geocaching (209,2 GB free) v2 internal isDir(6 entries)
- Legacy User storage c:geo dir: /storage/emulated/0/cgeo (209,2 GB free) v2 external non-removable isDir(6 entries)
- Geocache data: /storage/emulated/0/Android/data/cgeo.geocaching/files/GeocacheData (209,2 GB free) v2 external non-removable isDir(20 entries)
- Internal theme sync (is turned off): /data/user/0/cgeo.geocaching/MapThemeData (209,2 GB free) v2 internal isDir(0 entries)
- Public Folders: #9
- BASE: /cgeo (User-Defined)[/cgeo[DOCUMENT#0:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo, Av:true, files:>=6, dirs:>=7, totalFileSize:>=1,0 GB, free space: 209,2 GB, files on device: 12812795)
- OFFLINE_MAPS: /cgeo/maps (User-Defined)[/cgeo/maps[DOCUMENT#0:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo%2Fmaps::]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo%2Fmaps/document/primary%3Acgeo%2Fmaps, Av:true, files:4, dirs:1, totalFileSize:1,0 GB, free space: 209,2 GB, files on device: 12812795)
- OFFLINE_MAP_THEMES: /cgeo/maps/_themes (Default)[/cgeo/maps/_themes[PERSISTABLE_FOLDER(OFFLINE_MAPS)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo%2Fmaps::/_themes]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo%2Fmaps/document/primary%3Acgeo%2Fmaps%2F_themes, Av:true, files:0, dirs:0, totalFileSize:0 B, free space: 209,2 GB, files on device: 12812795)
- LOGFILES: /cgeo/logfiles (Default)[/cgeo/logfiles[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/logfiles]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Flogfiles, Av:true, files:1, dirs:0, totalFileSize:1,1 MB, free space: 209,2 GB, files on device: 12812795)
- GPX: /cgeo/gpx (Default)[/cgeo/gpx[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/gpx]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Fgpx, Av:true, files:1, dirs:0, totalFileSize:236,0 KB, free space: 209,2 GB, files on device: 12812795)
- BACKUP: /cgeo/backup (Default)[/cgeo/backup[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/backup]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Fbackup, Av:true, files:0, dirs:0, totalFileSize:0 B, free space: 209,2 GB, files on device: 12812795)
- FIELD_NOTES: /cgeo/field-notes (Default)[/cgeo/field-notes[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/field-notes]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Ffield-notes, Av:true, files:0, dirs:0, totalFileSize:0 B, free space: 209,2 GB, files on device: 12812795)
- SPOILER_IMAGES: /cgeo/GeocachePhotos (Default)[/cgeo/GeocachePhotos[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/GeocachePhotos]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2FGeocachePhotos, Av:true, files:0, dirs:0, totalFileSize:0 B, free space: 209,2 GB, files on device: 12812795)
- TEST_FOLDER: [Legacy]/data/user/0/cgeo.geocaching/files/unittest (Default)[/data/user/0/cgeo.geocaching/files/unittest[FILE#1:p-file:///data/user/0/cgeo.geocaching/files::/unittest]] (Uri: file:///data/user/0/cgeo.geocaching/files/unittest, Av:true, files:0, dirs:0, totalFileSize:0 B, free space: 209,2 GB, files on device: -1)
- Map render theme path:
- PersistedDocumentUris: #1
- TRACK: null
- Persisted Uri Permissions: #2
- content://com.android.externalstorage.documents/tree/primary%3Acgeo (21. März, 13:38):RW
- content://com.android.externalstorage.documents/tree/primary%3Acgeo%2Fmaps (21. März, 13:38):RW
- Database: /data/user/0/cgeo.geocaching/databases/data (v94, Size:832,0 KB) on system internal storage
-Settings: v5, Count:119
--- End of system information ---
```

A strange thing is, that both users have "HW-acceleration" disabled....mmmh

**Comment by Lineflyer** [comment]
Screenshot of second affected menu:
![grafik](https://user-images.githubusercontent.com/949669/116231587-5d0d1b00-a759-11eb-917b-50f220d878f0.png)

**Comment by bekuno** [comment]
> AFAIR we had this issue before...

This one https://github.com/cgeo/WhereYouGo/issues/66 ?

**Comment by moving-bits** [comment]
Haven't looked in the source yet, but I guess two possible problems:
- in current release version we still have styles based on device-specific templates (look for `Theme.DeviceDefault` in `themes.xml`)
- and we have some activities based on `Activity`, most based on `AppCompatActivity`

Both is fixed with #10049, which removes dependencies to `Theme.DeviceDefault` and bases all activities on `AppCompatActivity`. (This had been intended as a first small step towards #9373.)

Would be interesting to know what happens if the two users would use a nightly version - any chance?

**Comment by Lineflyer** [comment]
> Would be interesting to know what happens if the two users would use a nightly version - any chance?

Most likely not, as I don't want normal users to be forced onto the nightlies. I can however ask for volunteers.

**Comment by fm-sys** [comment]
I guess this issue is meanwhile fixed due to our complete theming redesign. Con we close here?

**Comment by Lineflyer** [comment]
Yes, if its still present with the upcoming version we will for sure get this reported again.
