### ISSUE TITLE
Save Waypoints: Remove rejection to store because of PN length

### ISSUE THREAD

**Issue by MagpieFourtyTwo** [cgeo/cgeo#10981]
## What function are you missing
I often use the [Store Waypoints] function to get the coords of all my WPs into the PN. Over there I usually edit the stuff, to create my own list of stages (with add. info). And afterwards the {c:geo} section may even be gone completely.

But, when my PN is already close to 2500 chars (which happens pretty often as we love to do challenging Multis and Mysteries), the function denies to store the WPs because of PN length - which makes no sense at all, IMHO, cause a) c:geo's PN is not limited anyway, and b) the length will just be an issue on upload, which will get an appropriate error message, anyway.

## Suggested solution
Add the WP storage to PN, no matter how long the PN will get (perhaps the WPs will just be stored to share them via messenger ...?), there may be a toast when the limit of 2500 chars is reached, but please just write them to PN as they are.

Moreover: Consequently following the storage procedure's rejection, c:geo must even forbid PNs with more than 2500 chars - which would of course be complete nonsense. ;)

**Comment by fm-sys** [comment]
How many characters can you upload to Geocaching.com? I guess this limit was implemented because of the PN upload functionality...

**Comment by Lineflyer** [comment]
2500 is the limit, but @MagpieFourtyTwo is totally right.
You can write a PN of length >2500 manually without a problem in c:geo. Why should we restrict the export of WP to PN if that limit is reached. 
The warning/error will show up once trying to upload it anyway.

**Comment by murggel** [comment]
While working on this issue, I realized, that c:geo is trying to fit the size-limit by shortening the note of each waypoint stepwise by 10 char (max 50 char), so all waypoints could be exported (but with truncated note).
If this still does not fit the size-limit, than the export is rejected. 

I would export the waypoints with complete note instead of reject the export, but don't know how to react in the first case, when the size-limit could be met with shortening the waypoint-note:
* shortening the waypoint-note  will fit the size-limit and all waypoints could be stored online in the PN , but the waypoint-notes are truncated for upload and gpx-export / archive-purpose
* not shortening the waypoint-note: on upload the last waypoints and also the {c:geo-end}-tag will be truncated but for gpx-export all waypoints with complete note for gpx-export / archive-purpose are available.

Possibilities:
* store complete waypoint-note - user has to shorten it by himself to decide which part is less important (probably we can add the shorten-character-count to the message)
* ask user, if the waypoint-notes should be truncated to fit the upload size-limit (probably store as setting - don't ask again)
* different button to export waypoint without size-limit

Any opinion or other suggestions?

**Comment by eddiemuc** [comment]
Ah, this was one of the first things I ever implemented for c:geo...

I would remove the shortening completely.

 Back in the days the limitation to max size of connector (e.g. 2500 in case of GC.com) was requested in the feature request. Even then I found this request strange, this is why I implemented the shorting to "ease" the effect of shortening. But the "shortening" goes along with loosing information (e.g. parts of the user note). And it overcomplicates things. And it can't prevent e.g. when a user adds own stuff later so size limit is not met again.

**Comment by MagpieFourtyTwo** [comment]
> I would remove the shortening completely.

Totally agreed.

I think it's always better to let the user decide instead of trying to implement an automatism that can never ever be better than manual action. Even more if the automatism can not be deactivated. Apart from that it's still not said that the note will be uploaded anyway ... WRT PN c:geo is way "better" than the server, so why cut off this advantage and limit ourselves? :)

**Comment by MagpieFourtyTwo** [comment]
And perhaps you can even have a look at the storage of owner-defined (unchanged) waypoints in the same go ...? ;)

**Comment by murggel** [comment]
> And perhaps you can even have a look at the storage of owner-defined (unchanged) waypoints in the same go ...? ;)

This will be tracked with #9083. I will have a look at that, but I am not sure, if there is an agreement on that....
