### ISSUE TITLE
Main screen search field not scrolling

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#12157]
### Describe your problem!

From support mail:

There is a bug in the latest version release 2021.11.21. I think the video linked in this email will tell it in the best but if you want to scroll the caches which are visited lately, it doesn' t do anything and if you close the keyboard it will close the list as well.

---

I know this bug was listed here and solved, but seems only to be solved on `master`.
Can we backport this into `release`?

### How to reproduce?

video removed due to personal data (location info)

Description:
On click into the search field the recent caches are shown but the last cache is cut off and its not scrollable.
Closing the keyboard also closes the result list.

### Reproducible

Yes

### c:geo Version

2021.11.21

### System information

```text
## System information

c:geo version: 2021.11.21

Device:
-------
- Device type: HD1903 (OnePlus7T_EEA, OnePlus)
- Available processors: 8
- Android version: 11
- Android build: HD1903_14_211021
- Screen resolution: 1080x2197px (384x776dp)
- Pixel density: 2.8125
- System font scale: 1.0 / used scale: 1.0
- Sailfish OS detected: false
- Google Play services: enabled - 21.42.18 (150400-410302452)

(Sent incomplete)
```

### Additional Information

Support ticket 813410

**Comment by fm-sys** [comment]
There where multiple commits involved in the progress of finally fixing that issue. I can look into the commit history and create a cherrypick PR if this is wanted...

**Comment by Lineflyer** [comment]
Might be wise as its currently a bit broken and the next release from `master` might take a while to be out.

**Comment by fm-sys** [comment]
> Might be wise as its currently a bit broken and the next release from `master` might take a while to be out.

First, I have to add that the situation has always been like that, IIRC. So at least, this issue shouldn't be a regression.


The original issue was fixed via 631b4a1b512b0d0a6ff729175d3282e6d350bce0, however that commit had introduced an even more weird and buggy behavior. That commit had the side effect, that the search view gets closed when clicking into the text field. Instead, the keyboard should get opened again if it is currently closed... (like you would expect when clicking into a text field)

That side effect was solved by 38daceca531ac1a1501b54448ed816a4b43a71f8, however that commit had to touch bottomnavigation code parts to solve that issue. For sure, it's theoretically possible to reapply the fix to non-bottomnavigation code, but this would be quite complex. We would have to create a totally new PR for release branch, and drop that commit again while merging branches back to master. Is that really worth the effort?

**Comment by Lineflyer** [comment]
I tested on 2021.10.08:
The existing problem is the fact, that the results are closed when you hide the keyboard, however scrolling in the results list was possible there.  That's why I named the issue just for the scrolling issue and its a regression indeed.

Anyway, if its not easily possible to bring this change onto `release` I am fine with closing here.

**Comment by MagpieFourtyTwo** [comment]
> First, I have to add that the situation has always been like that, IIRC. So at least, this issue shouldn't be a regression.

Nop, this has indeed changed: "In former times" (don't know exactly since when, as my cachemate pointed this out to me) it was most definitely possible to scroll the list. And, of course, it remained open even when the keyboard was closed.

And, yes, I remember these "former times" very well, as the search field is probably the function we use most often (to switch between the caches of the day and when looking for the next ones - which BTW is the reason why we would highly appreciate if the search filed function would be added as long click action for the search main activity ... but this is another issue ;) ).

**Comment by Lineflyer** [comment]
This is solved on `master` and decided not to be solved on `release`.

**Comment by MagpieFourtyTwo** [comment]
First of all: Thanks for pointing me to the issue (didn't remember the buzz word "scrolling" ;) ).

Nevertheless, sorry for asking a possibly dumb question, but what does this mean for the Nightlies?
Tried to the track down the correlations between ``master`` and ``release`` WRT the Nightlies, but did not really succeed,
at least not in a way which would explain why we can't see this ``master`` change in the Nightlies ...
Most probably my idea of the usage of ``master`` and ``release`` differs from the way, they are used in c:geo's repository ...?
Perhaps you can shed some light on this for my better understanding ...?  ;)

**Comment by moving-bits** [comment]
nightlies are dev-builds taken from current state of `master` branch, whereas `release` branch is totally separate from it.

At some point in time, when we decide to start a new beta, we copy the current state of `master` to a new `release` branch and create a beta from it. Some fixes may be added to that until finally an official version gets released from it. But there is no equivalent of a "nightly version" built from `release` branch.

So you will always have all fixes/changes from `release` included in `master` (and therefore in our nightlies), but not the other way around.

**Comment by Lineflyer** [comment]
@MagpieFourtyTwo 
This issue (see initial post) was about the search result not scrolling. That is solved in nightlies.
You probably refer to the initial items shown being limited/not scrolling (as you mentioned in another issue). That is still valid and should IMHO be filed into a dedicated issue.

**Comment by MagpieFourtyTwo** [comment]
@moving-bits
Thx for explaining - this is in fact the way I've already thought it would be. Goof to know that I was not *that* wrong. ;)
Nevertheless, I failed to reconcile this strategy with the statement that something has allegedly been fixed in Master,
but I still don't see it changed in the Nightly ... but obviously I just misinterpreted @Lineflyer's statement ...

@Lineflyer 
Ok, got it - so I just mis- (or even "over-")interpreted your "scrolling", as I was thinking of the results scrolling ...
However, will open a new issue for it.
And thx to you too, for the clarification.
