### ISSUE TITLE
Default TB log type to "visited" on directly logging a TB

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#14642]
Reported on support:

When using search => TB => log TB, default logging action seems to be random for yet unknown TB. For some it seems to be "grab", for others "discover". Request is to set the default to "visited" when logging a TB from the TB-specific page (resp. last action, when TB is already known).

Ticket numbers: 345502, 838122, 791319, 655197

**Comment by Lineflyer** [comment]
Could be a migration dependant issue.

**Comment by gcey** [comment]
IMO ist should be "discover", when logging a TB from the TB-specific page.
"Visit" only makes sense on cache logs.
"Grab" is a dangerous default, because it cannot be undone.

**Comment by moving-bits** [comment]
It's pretty nested code, but to my understanding it looks like it's doing this on loading a trackable from a search and starting to log it:
- retrieve trackable
- read list of available logging actions - the parsing involved here differs depending on an internal configuration setting
  - in my newly created emulator, the setting was unset, so it always used the new method. That one returned "NOTE" for a trackable which is my own, and "RETRIEVED_IT" + "DISCOVERED_IT" for a TB not yet logged by me => looks ok to me
  - if I force c:geo to use the old method, it returns an empty list as possible logging actions. This leads to "RETRIEVED_ID", "GRABBED", "NOTE" and "DISCOVERED_IT" as possible actions => ???
- c:geo then reads the last TB logging action you have used
  - if that is yet unset, RETRIEVED_IT is used, otherwise its value is checked against the available logging actions for this TB
  - if it is available for this TB, it gets set
  - if it's not available for this TB, c:geo uses the first entry in the list returned above

The only explanation I can think of currently is, that the affected users somehow have a value for the internal setting, so that c:geo uses the old method of determining the available logging actions, and that this old method no longer works.

@eddiemuc 
It looks you had introduced this switch (`Settings.enableFeatureNewGCLogApi()`) and usage of it in `TravelBugLoggingManager.loadInBackground()` - can you cross-check whether this switch can indeed be involved in giving unexpected results and whether this switch is still required at all?

**Comment by eddiemuc** [comment]
> eddiemuc It looks you had introduced this switch (Settings.enableFeatureNewGCLogApi()) and usage of it in TravelBugLoggingManager.loadInBackground() - can you cross-check whether this switch can indeed be involved in giving unexpected results and whether this switch is still required at all?

This switch was introduced recently to distinguish between the "old" and the "new" log workflow of GC.com. As soon as the new workflow has proven to be stable for all users in prod it can be removed. This shall happen together with the old workflow's   code which is then no longer used.

I kept the switch for two reasons (same as always):
- in case the (big!) change in logic would have a serious bug in Production. Then support/user has a chance to deactivate
- as a reminder to remove legacy code later when new code is stable

Especially when old workflow does no longer work, then switch can be removed safely.

Users affected by the bug can be asked whether the set the switch property to false.

**Comment by capoaira** [comment]
Ok, where I can find the switch to use the new logging? I didn't find it in the logging settings. I use version 2023.11.13

**Comment by eddiemuc** [comment]
> Ok, where I can find the switch to use the new logging? I didn't find it in the logging settings. I use version 2023.11.13

It is a hidden property, it is not settable via GUI. It is called `feature_new_gc_log_api` and of type boolean. If you don't know how to set it then I doubt much that it is set on your device. To check you may go to `c:geo Settings` -> `System` -> `View Settings`. In the (long) list of settings, you may search for an entry `feature_new_gc_log_api`. If it exists and is set to false then you may remove it or set it to true. 

Here is an example screenshot of the settings list on my device. On my device the setting is NOT present, this should be the case on your device as well

![image](https://github.com/cgeo/cgeo/assets/6909759/fc8214f2-2cf5-48c4-8f49-aafbde3ebea2)

**Comment by capoaira** [comment]
Your right, I don't have this property. I try to set it manually but this change nothing. I think my version don't have the property,  but the bug.

For me it is not a big problem, since I don't log TBs anymore. 

I can attach my systems information if that helps.

**Comment by eddiemuc** [comment]
What might be noteworthy:
* c:geo only stores one "global" last trackable log type and tries to apply this as default on next log
* the last trackable log type is only stored when a log is actually sent

PR #14851 introduces a logic where in case the default log type is not available, then c:geo searches a list of preferred default tb log types (instead of just taking the first one returned from the server). This PR is on release. I can't test it because I don't really wok with TBs.

I also created PR #14850 to remove legacy GC log code. This PR is against master. Before it is brought to production it should be tested in nightlies and beta to ensure nothing was missed.

**Comment by moving-bits** [comment]
Merged a fix (#14851) to nightly version, so let's close here. Feel free to reopen if something still not working in this context.

**Comment by capoaira** [comment]
Hello,
the mentioned behavior above still exists in the new version (2023.12.21)
When I try to log B9W5FD it show me first "Mitgenommen" (Take it) and then it switch  to write note.
The excepted behaviour should be "discovered"

Happy Christmas 🎄  to everyone :)

**Comment by gcey** [comment]
I completely agree to capoaira's comment.
Who can please reopen the issue?

**Comment by moving-bits** [comment]
@eddiemuc 
IIRC you created the last fix for TB default action, can you have a look at it (if time permits)?

**Comment by eddiemuc** [comment]
Hopefully fixed with #15082

**Comment by capoaira** [comment]
With the new version it works.  Thank you for your effort. 👍🏻

**Comment by Lineflyer** [comment]
Thanks @capoaira for your feedback. I assume we can close then...

**Comment by gcey** [comment]
Unfortunately the issue is still not solved completely.
When I want to log e.g. the TB "SXJ7E5", I still get "MITGENOMMEN" (RETRIEVED_IT) instead of "GESEHEN" (DISCOVERED_IT).
Who can please reopen the issue?

**Comment by Lineflyer** [comment]
It should now remember the logtype you once selected, so you might need to manually set it to discover once and it should be remebered from then on.

**Comment by gcey** [comment]
Let's try:
  *  Search the TB "SXJ7E5".
  *  (By the way: Why doesn't c:geo show, in which cache the TB is currently?)
  *  Log it
  *  c:geo shows "MITGENOMMEN" (RETRIEVED_IT)
  *  Change it to "GESEHEN" (DISCOVERED_IT)
  *  Write some text and send the log.
  *  Search the TB "AJ0WBM".
  *  (Again c:geo doesn't show, in which cache the TB is currently)
  *  Log it
  *  Again c:geo shows "MITGENOMMEN" (RETRIEVED_IT) instead of "GESEHEN" (DISCOVERED_IT)

So the issue is still not solved.
Who can please reopen the issue?

**Comment by eddiemuc** [comment]
> By the way: Why doesn't c:geo show, in which cache the TB is currently?

Is this a feature which was available in the past (and is now gone)?

**Comment by Lineflyer** [comment]
I can confirm the missing state info (what cache / who carries it), this is a regression indeed. Will open a dedicated issue for that.

But in the above scenario for both TBs the logging windows defaults to "Gesehen" for me.

**Comment by eddiemuc** [comment]
PR #15214 reworks the whole logtype assignment logic in the activity and hopefully now finally fixes the problem
