### ISSUE TITLE
[Nightly] GMap+GSat: Route to cache opens map at N00 00.000 W000 00.000

### ISSUE THREAD

**Issue by MagpieFourtyTwo** [cgeo/cgeo#16556]
### Describe your problem!

If map is set to Google Satellite or Google Map, a click on the icon ``Navigation tool`` in the header of a cache opens the map at N00 00.000 W000 00.000.

The route is correct, as you can see after pressing ``Go to my position``

### How to reproduce?

1. in the settings set ``Navigation tool`` to ``Map``
2. go to map view and select GMap or GSat
3. open any cache
4. tap on the round ``Navigation tool`` icon in the header

### Actual result after these steps?

Map opens at N00 00.000 W000 00.000.

### Expected result after these steps?

Map should open at the cache coordinates (like it does in OSM offline).

### Reproducible

Yes

### c:geo Version

2025.01.12-NB-965ae79

**Comment by eddiemuc** [comment]
I confirm that there was this bug (same as reported in #16549), but I supposedly fixed it in #16550  which was merged at 11.1. sometime in the afternoon. With this fix applied I am not able to reproduce. Is this really still happening on 12th Januaries nightly?

**Comment by MagpieFourtyTwo** [comment]
Yep

**Comment by MagpieFourtyTwo** [comment]
But perhaps only since a few days ... at least I just stumbled upon it yesterday. But I don't use GSat a lot (GMap as good as never), and esp. not for routing/navigation. 

99.99 % of the time I am in OSM Offline and just shortly switch to GSat to have a look at the surroundings of the spot and immediately switch back to OSM. This time I just forgot to go back to OSM before I went back to the listing.  And I would say, even this worked up to yesterday ... but can't say for sure ...

**Comment by eddiemuc** [comment]
> But perhaps only since a few days ... at least I just stumbled upon it yesterday. 

@MagpieFourtyTwo if you stumbled upon this yesterday, then it could not have been version 2025.01.12-NB-965ae79; that one was created overnight from yesterday to today. in yesterday's daily (2025.01.11-NB-63e56df) the bug is confirmed. In todays nightly (2025.01.12-NB-965ae79) it should be fixed (except if I didn't fix it correctly...) 

So is the problem really still present for you in 2025.01.12-NB-965ae79?

**Comment by MagpieFourtyTwo** [comment]
You are right - nevertheless, I don't really understand ... I tested it again this morning with yesterday's nightly (with a different cache), then updated to the current nightly and tested again ... and as the problem still existed (in my world) I then decided to file the issue ...

Strange.  However, then we can close here.  Even better.  ;)

**Comment by eddiemuc** [comment]
> You are right - nevertheless, I don't really understand ... I tested it again this morning with yesterday's nightly (with a different cache), then updated to the current nightly and tested again ... and as the problem still existed (in my world) I then decided to file the issue ...

I have a probably explanation: when in yesterdays faulty build the location changed to 0-0, then c:geo remembered this position. When you change to the map again it would open there again, even with the new (hopefully less-faulty) build.

**Comment by MagpieFourtyTwo** [comment]
Nice of you for trying to explain my testing failure (really appreciate it :) ) but although it sounds reasonable, it's not possible, as for the second test I of course did it the same way, i. e. via opening a cache and using the navigation tool icon ... still don't get what has happened. Guess I have to live with it. I hope this was a unique malfunction and not a sign of getting lost of testing abilities. ;)
