### ISSUE TITLE
[Nightly] Logging behaves strange ...

### ISSUE THREAD

**Issue by MagpieFourtyTwo** [cgeo/cgeo#17135]
### Describe your problem!

Has something been merged tonight that deals with either 
- logging or
- text window padding or
- sending logs or
- refresh of esp. logs?

Made two observations today:
- When logging a note, there was no more padding, it even looks as if the padding value is negative, as the letters at the edges are even partially covered by the text box outline - which looks pretty weird and makes it hard to select e. g. the position in front of the first letter of a line
- After posting the log, it appeared twice in the list of logs. Refresh did not change anything, the log is still doubled. Online there is only one log ...

Additionally deleted the cache, closed c:geo and started from scratch, but no change.

### How to reproduce?

1. Log any cache - and pay attention to the padding (you will notice that there is none at all)
2. Post the log ...

### Actual result after these steps?

The log appears twice in the list of logs.

### Expected result after these steps?

a) Padding should be big enough to see some "blank space" between letters and text frame border
b) Log should appear only once

### Reproducible

Yes

### c:geo Version

2025.07.14-NB-71e01cc

### System information

```text

```

### Additional Information

I'm pretty sure that this was not the case yesterday. Although I have not posted a log from within c:geo, at least the padding was most definitely there yesterday (made several offline logs).

**Comment by murggel** [comment]
Damn - probably again my change?
#17080 was merged, which deals with merging online logs...
Will have a look

**Comment by MagpieFourtyTwo** [comment]
Moreover the TB button ``Change all`` looks pretty weird ... although I can not say, since when this is the case ...

![Image](https://github.com/user-attachments/assets/11becab3-2f77-4009-b191-1ec37f481a1f)

**Comment by MagpieFourtyTwo** [comment]
Please don't take it personally ...  ;)

**Comment by murggel** [comment]
PR  #17136 should fix the doubled log and remove it on refresh

**Comment by murggel** [comment]
> Moreover the TB button `Change all` looks pretty weird ... although I can not say, since when this is the case ...
> 
> ![Image](https://github.com/user-attachments/assets/11becab3-2f77-4009-b191-1ec37f481a1f)

Fine on my emulator ...

<img width="569" height="513" alt="Image" src="https://github.com/user-attachments/assets/224f9e2d-7809-47ef-a68b-4b916c02e8ea" />

@moving-bits Probably related to the changes regarding SDK 35?

**Comment by MagpieFourtyTwo** [comment]
Hmm, strange.  And what about the padding in the log text box?

**Comment by murggel** [comment]
> Hmm, strange.  And what about the padding in the log text box?

Also not on my device

**Comment by MagpieFourtyTwo** [comment]
Guess we have to file a new issue for the boxes stuff - things behave even more strange in the waypoint dialogue.  And as these came all together, the SDK change appears to be a good approach to me.

WRT log doubling: I wrote a note for a cache today and after posting it, it first still appeared doubled. I needed to refresh the cache another time to get rid of the sibling.

**Comment by murggel** [comment]
> WRT log doubling: I wrote a note for a cache today and after posting it, it first still appeared doubled. I needed to refresh the cache another time to get rid of the sibling.

Strange - will have a look at it

**Comment by bekuno** [comment]
> Guess we have to file a new issue for the boxes stuff - things behave even more strange in the waypoint dialogue.  And as these came all together, the SDK change appears to be a good approach to me.

Is your device on Android 15?

**Comment by MagpieFourtyTwo** [comment]
Yep

**Comment by murggel** [comment]
> > WRT log doubling: I wrote a note for a cache today and after posting it, it first still appeared doubled. I needed to refresh the cache another time to get rid of the sibling.
> 
> Strange - will have a look at it

@MagpieFourtyTwo  can't reproduce it on the emulator, can you provide your steps, please. Do you send the log / note immediately or store it first as offline log / note? What logs did you send before? A found log?

**Comment by MagpieFourtyTwo** [comment]
Was an immediate ... no, once stored, then slightly edited and then posted Write Note for a cache I already found a while before.

I will recheck with my next Will Attend. Or will write a note to a fellow's cache. ;)
