### ISSUE TITLE
Adding geocaches to bookmark often fails w/o explanation

### ISSUE THREAD

**Issue by eddiemuc** [cgeo/cgeo#17169]
Taken from support: https://cgeosupport.droescher.eu/scp/tickets.php?id=9265 
Reproduced by me with 2025.07.17

When using "add selected (caches) to bookmark list", the behavior is very shaky.
* In first step c:geo retrieves and shows a list of existing bookmark lists. Thus usualy works fine
* After choosing a list, then very often the process afterwards fails for no obvious reasons with error message "Fehler beim Hinzufügen von Caches zur Lesezeichenliste"

I could reproduce the problem easily while having good internet connection and being logged in as PREMIUM several times. I found following exception in log:

```
07-22 17:33:24.620 25288 27733 E cgeo    : [OkHttp] GCParser.uploadPersonalNote - cannot upload caches to GC.com bookmark list
07-22 17:33:24.620 25288 27733 E cgeo    : java.io.IOException: unsuccessful response: Response{protocol=http/1.1, code=401, message=Unauthorized, url=https://www.geocaching.com/api/proxy/web/v1/lists/BM7D93C/geocaches}
07-22 17:33:24.620 25288 27733 E cgeo    : 	at cgeo.geocaching.network.Network.$r8$lambda$wUQJhvGOfGQvK1C_-6clmCSzy0k(SourceFile:705)
07-22 17:33:24.620 25288 27733 E cgeo    : 	at cgeo.geocaching.network.Network$$ExternalSyntheticLambda5.apply(SourceFile:0)
07-22 17:33:24.620 25288 27733 E cgeo    : 	at io.reactivex.rxjava3.internal.operators.single.SingleFlatMap$SingleFlatMapCallback.onSuccess(SourceFile:77)
07-22 17:33:24.620 25288 27733 E cgeo    : 	at io.reactivex.rxjava3.internal.operators.single.SingleCreate$Emitter.onSuccess(SourceFile:68)
07-22 17:33:24.620 25288 27733 E cgeo    : 	at cgeo.geocaching.utils.RxOkHttpUtils$1.onResponse(SourceFile:48)
07-22 17:33:24.620 25288 27733 E cgeo    : 	at okhttp3.internal.connection.RealCall$AsyncCall.run(SourceFile:519)
07-22 17:33:24.620 25288 27733 E cgeo    : 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1156)
07-22 17:33:24.620 25288 27733 E cgeo    : 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:651)
07-22 17:33:24.620 25288 27733 E cgeo    : 	at java.lang.Thread.run(Thread.java:1119)
07-22 17:33:24.621 25288 25288 I cgeo    : [main] [cgeo.geocaching.CacheListActivity].showToast(Fehler beim Hinzufügen von Caches zur Lesezeichenliste){LONG}
```

I see two problems here:
* "shakyness" of process. It is not obvious why this is happening. I noticed that code in `BookmarkUtils` somehow uses its own "authentification mechanism" (?) or probably relies on cookiejar (?). Code might be more stable if mechanisms eg of `GCAuthApi` are used?
* Feedback to user is improvable. After selecting a bookmark list there's no indication that upload takes place. Also, when process fails it is not shown to the user how many of the selected caches were successfully uploaded before process breaks

**Comment by eddiemuc** [comment]
Update: user gives feedback that probably he tried to store a lab cache in bookmark list. This apparently is not supported by gc.com. But c:geo should display an according error message in this case (or prevent lab caches to be used with this function in the first place)

**Comment by JakeDot** [comment]
Happened to me lots of times. Also confusing in this context is that gc bookmark lists only allow 1000 entries, if you try to store more it will give you a generic error message but still creates / inserts up to 1000 to the list (which takes a few seconds to show the message).

**Comment by ztNFny** [comment]
> * It is not obvious why this is happening. I noticed that code in `BookmarkUtils` somehow uses its own "authentification mechanism"

it does - because that's how GC designed it - it's a separate CSRF token :-(

> Also, when process fails it is not shown to the user how many of the selected caches were successfully uploaded before process breaks

That info isn't available, it's not returned by the service. Caches are added as a batch operation.

AL caches are not the cause for any failures, the code to add caches to a list will only run on real GCs, not on OC, AL, ...

**Comment by ztNFny** [comment]
We could probably expand CacheDownloaderService / provide a new service to provide a general UI for ongoing background activities to make actions like this more transparent to the user. Could be a simple "Show notification with text XYZ and X of Y items" service that can be called from various places like adding to bookmark lists. Haven't yet worked with services and the CacheDownaloderService seems quite complex - @fm-sys any chance you'd feel like providing a simple wrapper service to be used for various background operations?

**Comment by fm-sys** [comment]
Unfortunately there is pretty much nothing more to abstract. AbstractForegroundIntentService is already the superclass you are looking for.

(Furthermore it doesn't feel right to use a foreground service for really short running tasks. Intended usecases are things like a music player app which should keep playing or recording an outdoor track over hours. Most importantly, there is clearly a bug in our API call which won't be fixed by moving it into a foreground service.)

**Comment by ztNFny** [comment]
Which bug in our call? From the discussion here i don't see any. 

What alternative is there to show a progress notification then?

**Comment by fm-sys** [comment]
Ah, got it. You are thinking about a "batch operation" foreground service abstraction. So your idea is to add every single cache by it's own API call? Not sure if this is a good way. We could check instead which / how many caches are already in the bookmark list...

**Comment by ztNFny** [comment]
>  You are thinking about a "batch operation" foreground service abstraction.

Yes

> So your idea is to add every single cache by it's own API call?

No!
I was refering to "Feedback to user is improvable. After selecting a bookmark list there's no indication that upload takes place." which could be improved by showing a notification that the operation is in progress - and the same notification could be used in plenty of other places as well, e.g. for "upload modified coordinates" batch operation in lists.

> We could check instead which / how many caches are already in the bookmark list...

We could indeed show a dialog "only X of Y caches can be added to the list" confirmation prompt, that's easy to do, all the info is already there. I wouldn't block the operation per se.

**Comment by ztNFny** [comment]
I've now added a warning on adding too many caches and an info about the cache count per list.
@eddiemuc Is it possible in SimpleItemLists to disable entries? Imho it'd be nice to still show a list with 1000 caches on it but to have it greyed out.

**Comment by eddiemuc** [comment]
> I've now added a warning on adding too many caches and an info about the cache count per list. [@eddiemuc](https://github.com/eddiemuc) Is it possible in SimpleItemLists to disable entries? Imho it'd be nice to still show a list with 1000 caches on it but to have it greyed out.

`SimpleDialog` allows disabling of buttons (OK and Cancel in this case I assume) based on whether something is selected or not. This is done via `SimpleDialog.setButtonSelectionIsMandatory()`. The inner logic is applied in `SimpleDialog.adjustButtonEnablement`. This could easily be extended to check for arbitrary conditions (e.g. "more than x caches selected")

`SimpleDialog` also allows adding a message above the selection if this is wanted.

It does not allow diasbled display of items though. That would probably not work well together with the "select all" feature too.

**Comment by ztNFny** [comment]
> It does not allow diasbled display of items though.

That's what I was looking for. Wouldn't know any other usecase where it's useeful to have this, so question is whether it's worth implemeting
