### ISSUE TITLE
Cache not added to history if unsaved and logged from popup

### ISSUE THREAD

**Issue by Bjurran** [cgeo/cgeo#4086]
Been running the latest nightly builds for som time now and there's one annoying bug with the ones I've used this week. The history doesn't contain all the offline logs resulting in missing found logs when exporting the feild notes. I noticed this the first time July 16th and it's the same today.
All caches are saved and updated on the phone prior to caching.
The offline logs are saved and I'm able to open the logs from the individual caches, but they simply don't appear in the history.
Today 2 of the caches are not shown, last time it was 3 or 4.
Currently running 2014-07-18-NB1-0822830 and can confirm that the bug is still there.

**Comment by MrYaz** [comment]
I know that there are many people that suffer from this bug and as a consequence doesn't use the History at all. Please change priority of this bug if possible.

**Comment by Lineflyer** [comment]
Raising priority as we get quite some complaints where offline logs have been lost due to this reason!

**Comment by Lineflyer** [comment]
It might even get worse:
A chat with a user made me aware that caches logged offline under that condition might stay forever in the database (making it increasing) without beeing visible to the user in any list (not saved=not in lists, not in history).
Only by explicitly loading them (e.g. by GC-code) the user would bring those caches back into the normal cycle.

**Comment by Lineflyer** [comment]
Complaints keep coming in on support mail. So either users have started using this usecase or another manifestation of this issue has been introcuced recently.

**Comment by Lineflyer** [comment]
Here is a (german) description of that problem from FB.
Maybe the hint that the logged date is missing is the clue for finding the root cause why it is not listed in the history:

[...]normal steht dann wenn man den Cache geloggt hat und das Listing aufmacht als Status "Gespeicherter Log und das DATUM" z.B. Gespeicherter Log 11.08.2015 wenn man den Cache loggt, ohne ihn vorher zu speichern steht nur "Gespeicherter Log" also ohne Datum daher scheint er wohl dann auch im Verlauf nicht gelistet zu werden.

**Comment by MrYaz** [comment]
I have also found that a cache is not added to the History list when long-pressing on it's name in a list and selecting Log visit. 
It does not add the Logged date in that case either.

Cache that was logged via Cache details - with Logged datum:
![image](https://cloud.githubusercontent.com/assets/1811963/9294236/27a7f48c-4448-11e5-9876-3d459bbb0bd9.png)

Cache that was logged via popup menu in List view - missing Logged datum:
![image](https://cloud.githubusercontent.com/assets/1811963/9294240/5f82035c-4448-11e5-9390-8b29b4e2f9ca.png)

Both marked as found in List:
![image](https://cloud.githubusercontent.com/assets/1811963/9294234/f826780a-4447-11e5-8039-c5e96a34b24d.png)

Only cache that was logged via Cache details is listed in History:
![image](https://cloud.githubusercontent.com/assets/1811963/9294247/a5b9e376-4448-11e5-8f68-078881e07913.png)

I hope that this helps identifying the bug and squashing it once and for all.

**Comment by Bjurran** [comment]
2015-08-17-NB-c65e413
This happened again. 1 event, 1 traditional and 1 unknown. The unknown is not visible in the history, but it is saved and if I open the cache it clearly states that there's a saved log.

**Comment by MrYaz** [comment]
First of all, sorry for nagging...

But can someone of the developers, @samueltardieu @Bananeweizen @Lineflyer @rsudev  @kumy,  tell me why this bug has not been fixed yet?
It is one of five issues at the moment with both the labels High and Bug so I think it is severe enough to be prioritized. Don't you think?

I think that the offline logging feature is really great in c:geo and I find it sad to hear about friends that avoids using it because they have been "burned" after loosing Found logs because of this particular bug.

**Comment by samueltardieu** [comment]
Sure, I can explain why it is not fixed yet: nobody has submitted a patch for it. And nobody has offered a bounty either to encourage a new developer to jump in the boat and fix it. This is as simple as that.

**Comment by Lineflyer** [comment]
As @samueltardieu described.
The `high` flag only gives some indication of which bugs might be the first ones to tackle if someone is interested in helping with bugfixing and cannot give a guarantee of a certain fixing time. But it also shows that we understood the priority of this bug.

**Comment by Lineflyer** [comment]
Many many complaints on support regarding this issue. It would be really helpful if this can be fixed.

Meanwhile I can reproduce it quite good:
If a cache is not details (i.e. only loaded via live map) and the user opens the popup on the map and selects Menu - Offline log - Found it wont be added to the History list as it is not stored in our DB

This seems to be a very common online usecase (just work with live map, no stored caches and just save the found info for later on).

The "easiest" way here would be IMHO to store it at least to our "cached caches list" when the user triggers some logging actions.

**Comment by samueltardieu** [comment]
Since we only save a cache when we have information about it (*e.g.*, its description), we would not be able to save such an incomplete cache if there is no network for example, thus preventing logging completely. I have not worked with the history before (and I don't use it much myself), but maybe the unsaved cache could be put in history anyway.

**Comment by Lineflyer** [comment]
The main issue for me here is, that at some point of time it was working (so it is a regression). Although this issue is quite olf the problem as it is today is newer (the orginal case was solved, then reoccured unreproducible, then a new scenario appeared).

**Comment by alex7654** [comment]
I also encountered this bug, which is fully reproducable to me. I really would appreciate, having it resolved. If I can assist in testing, please, let me know.

**Comment by Lineflyer** [comment]
This is really one of the long runners which I ofter get confronted with on support mails.
Can anyone try to tackle this?

Here is a recent support mail (extract):

I haven’t heard much about this issue since opening my ticket back on 4/9/2015.  I was burned by using the store logs offline feature at that time and really haven’t used it much since.  This past weekend I did a power trail in Oklahoma and was thinking the feature was fixed.  Haha…

When I got home, I used the filter option in Cgeo to pull up all caches with offline notes.  86 caches came up.  Hum, I know that is not correct for I just knew we found more.   Here is what I found and hopefully this will help solve the issue.
[...]
When I pulled up the filter option to find caches with offline logs.  The filter pulled up only those caches that I had loaded to my phone before the trip.  They were offline caches, even though I was using the live map feature in Cgeo to cache by.
[...]
Those caches I found and put an offline log on, that were not load previously, in other words, were on my live map view as real time, those caches were not found by the filter HOWEVER, if I used the search function in Cgeo, either by name or GC code, they were found and my notes were still there.  Just had to find each one manually, which was a huge pain. 

So again, I was burned by the offline log feature

If the programmers want Cgeo to continue to be used by geocachers, this year old issues really needs to be resolved.

**Comment by samueltardieu** [comment]
One obvious solution would be to disable logging and navigation from the popup. But that would probably not be the most friendly way.

**Comment by Bjurran** [comment]
It's been more than 2 years since I started this thread. Any progress here? 
Version 2016.08.27, same issue still.
Downloaded two caches (one traditional, one mystery) to a list to be certain I had all data. Saved the logs as offline logs, and none of them are visible from found caches. If I go to the live map they are shown with a red smiley.

**Comment by Lineflyer** [comment]
Hi @Bjurran 

> It's been more than 2 years since I started this thread. Any progress here? 

No, sadly no one of our small team had the time to research/debug this issue.

> Downloaded two caches (one traditional, one mystery) to a list to be certain I had all data. Saved the logs as offline logs, and none of them are visible from found caches. If I go to the live map they are shown with a red smiley.

That is strange compared to the latest clues we had on this issue:
IMHO only unsaved caches should be affected and only if the are logged from the popup window on live map. In your case non of these conditions apply. Are you sure...I am doing the same thing all the day when caching and don't miss a cache in the history.

**Comment by Bjurran** [comment]
> That is strange compared to the latest clues we had on this issue: IMHO only unsaved caches should be affected and only if the are logged from the popup window on live map. In your case non of these conditions apply. Are you sure...I am doing the same thing all the day when caching and don't miss a cache in the history.

I had to read my old posts regarding this and as far as I can tell, I've had issues with caches saved back in 2014. This time, I know for a fact that the traditional was saved from the live map, and the mystery was saved by searching for the GC and saving it. I know I had all the data as it was shown on the correct position on the map as I was close enough to use the live map while driving towards it.

**Comment by pstorch** [comment]
Interesting bug. Just did some short investigations.

The History list searches for geocaches in table `cg_caches` with `visiteddate > 0` and `detailed = 1` (optionally filtering by cache Type).

If saving an offline log without prior saving the cache only an entry in table `cg_logs_offline` is added. So it can't find it.

If you save the cache and the offline log from the Map popup the `visiteddate` is not set correctly. Don't know yet, why.

I would like to continue on this one.

**Comment by Lineflyer** [comment]
That would be great. It seems detailed=1 is the first problem as unsaved caches with offline los might be missing on history then.
-------- Ursprüngliche Nachricht --------Von: Peter Storch <notifications@github.com> Datum: 31.08.16  00:09  (GMT+01:00) An: cgeo/cgeo <cgeo@noreply.github.com> Cc: Lars <gc@droescher.eu>, Mention <mention@noreply.github.com> Betreff: Re: [cgeo/cgeo] Cache not added to history if unsaved and logged from popup (#4086) 
Interesting bug. Just did some short investigations.

The History list searches for geocaches in table cg_caches with visiteddate > 0 and detailed = 1 (optionally filtering by cache Type).

If saving an offline log without prior saving the cache only an entry in table cg_logs_offline is added. So it can't find it.

If you save the cache and the offline log from the Map popup the visiteddate is not set correctly. Don't know yet, why.

I would like to continue on this one.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/cgeo/cgeo","title":"cgeo/cgeo","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/cgeo/cgeo"}},"updates":{"snippets":[{"icon":"PERSON","message":"@pstorch in #4086: Interesting bug. Just did some short investigations.\r\n\r\nThe History list searches for geocaches in table `cg_caches` with `visiteddate \u003e 0` and `detailed = 1` (optionally filtering by cache Type).\r\n\r\nIf saving an offline log without prior saving the cache only an entry in table `cg_logs_offline` is added. So it can't find it.\r\n\r\nIf you save the cache and the offline log from the Map popup the `visiteddate` is not set correctly. Don't know yet, why.\r\n\r\nI would like to continue on this one."}],"action":{"name":"View Issue","url":"https://github.com/cgeo/cgeo/issues/4086#issuecomment-243597428"}}}

**Comment by Lineflyer** [comment]
Just some more thoughts:
It might be a straight forward plan to trigger saving the cache as soon as an offline log is added. That will avoid any necessary case destinctions.
AFAIR we do the same if personal notes are added on an unsaved cache

**Comment by pstorch** [comment]
@Lineflyer I was thinking about that, too.

**Comment by rsudev** [comment]
There is unfortunately a fundamental difference between the personal note and the popup case - in the personal note case we have the full details (even already in the database if I am not mistaken) and we just need to 'store' it (assign the standard list). In the case of the popup this might not be true and AFAIK is our code tailored to expect only caches with full details in the database.
So for the popup we have two cases IMO:
# cache is saved/has full details: If necessary store it to standard list and 'just' fix the ```visiteddate``` handling
# cache is not fully detailed: I guess here we have no chance other than to revisit our data flow to enable all parts to correctly handle partially available caches...

**Comment by Bjurran** [comment]
Glad to see that you are getting closer. I just wanted to ask if any of you have experienced this after importing a gpx? I haven't had time to test that myself. 
(just in case there's any difference between importing or saving from the map or searching)

**Comment by pstorch** [comment]
I made a small test with saving the cache if not saved yet, before writing the log. I had to use the `Geocache.store()` method which also downloads the details if necessary. `DataStore.saveCache()` which is used in `CacheDetailActivity.ensureSaved()` wasn't sufficient.

Open issue: when the Phone has no internet connection (e.g. Airplane mode). Then we can't download the missing details and are not able to store the Cache. But we still write the offline log. In this case it's still missing in the History list.

Another strategy could be that the History list also looks in the offline logs table and merges them into the List (if missing). But then we would miss some Data which is present in each list entry.

@Bjurran I use GPXs (Pocket Queries) most of the time and can store offline logs, which show up in History.

**Comment by rsudev** [comment]
@pstorch Downloading the details in case of offline logging is IMO not an option. It just takes too much time when it works and has a high chance of not working at all. Of course this is true whenever you download a cache 'in the field', but then it is an explicit action/choice made by the user, not something that just happens.
And writing an offline log for a cache which is just in memory doesn't sound like an awfully good idea either...

**Comment by pstorch** [comment]
@rsudev yes, it needs some time. Maybe too long to be acceptable. I've done it Async at the moment, but this has other drawbacks.

What else can we do? 
Forbid offline Logs if the cache has not been saved before? Not user friendly either.
Redesign the offline logs table to also contain some basic information about the Cache (e.g. title, type, ...) to be able to show it in the List activity.

Other ideas?

**Comment by pstorch** [comment]
Why do we only save caches where `detailed = true`? We have this flag in the DB and can react on it.
I've made some tests and allowed to save the cache without detailed information. Then the save is fast (doesn't need to download anything) and it shows up in the History.
The CacheDetails can still be opened and details loaded afterwards with `refresh`. 

Still sometimes the `visiteddate` is not set correctly. I can't find out why, yet. I suspect some race conditions. I'll continue with tests.

**Comment by rsudev** [comment]
The history behind this is, that initially all caches were saved in the database always, even the live-map caches. This led to performance issues, and I assume one of the ways to avoid accidental save of a cache to the database was, to explicitly require ```detailed = true```.
It is good to hear that it does not lead to immediate problems, if this restriction is lifted, but we should be careful, that this does not lead to flooding the database with partially downloaded caches.
Perhaps we can require 'personal information' (like an offline log) in addition?
