### ISSUE TITLE
Next bugfix release

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#5121]
The `release`branch contains quite some important fixes. Therefore I suggest to release after this weekend. I just built a RC version for me to test (and maybe to share on FB later on).

Changes so far:
- Fix: Possible crash while editing personal notes
- Fix: Waypoints of caches may be missing on GPX import
- Fix: Crash if talking compass is started without target
- Fix: Request to gc.com tile server sent for caches from unknown sources

Opinions?

**Comment by mucek4** [comment]
@samueltardieu is off, I am off till end of weekend and we don't wanna screw weekend. Put RC to FB, and if all goes ok, we go live on monday?

**Comment by Bananeweizen** [comment]
+1

**Comment by Lineflyer** [comment]
Tested over the weekend and it was OK.
Published RC link on FB now.

**Comment by Lineflyer** [comment]
No negative feedback.
So we can release tomorrow if no one objects.
Staged or not?

**Comment by Lineflyer** [comment]
Published to 10% as agreed on IRC:

**Comment by Lineflyer** [comment]
No relevant crashes visible on the Google Play Console and >500 users online.
If someone with access to Google Play reads this and agress, he should set the release to 100% then.

**Comment by SammysHP** [comment]
Done.

**Comment by Lineflyer** [comment]
Thanks.
Release notification posted via status as the release is available to me on Play now (and wasn't during the staged phase).
However tagged it on Github and uploading the APK here is still missing, therefore reopening.
Maybe someone can tag it so I can attach the APK accordingly.

**Comment by Lineflyer** [comment]
By the way: FB posting scheduled for 08:40 GMT+2 tomorrow morning,

**Comment by kumy** [comment]
@Lineflyer I'll add the tag market_20150803 and do "Update Github releases and milestones" from doc https://github.com/cgeo/cgeo/wiki/Prepare-a-release

**Comment by kumy** [comment]
Done.
@Lineflyer I think it's good, I'll let you check, then close.

**Comment by Lineflyer** [comment]
Looks perfect to me. Thanks @kumy 
You did take the APK from the website not something self compiled, etc...?

**Comment by kumy** [comment]
@Lineflyer APK was taken at download.cgeo.org/cgeo-release.apk (seen that in CI ;))
