### ISSUE TITLE
Only first log image loaded

### ISSUE THREAD

**Issue by SammysHP** [cgeo/cgeo#5562]
##### Detailed steps causing the problem:
- Open http://coord.info/GC5MF1T
- Open log images for the log from TX-Tracker

##### Actual behavior after performing these steps:
Only the first image is shown.

##### Expected behavior after performing these steps:
Both images should be shown.

##### Version of c:geo used:
2016.03.20-null-20cccf9

##### Is the problem reproducible for you?
Yes

**Comment by mcastellini** [comment]
Looks like this issue is still present, c:geo version 2016.04.12 still shows the same behaviour.

**Comment by SammysHP** [comment]
This was fixed only in the development (master) branch and is included in the nightly builds since 2016-03-23. The release is some weeks behind the current development because changes are tested in nightly builds first.

**Comment by mcastellini** [comment]
I'm sorry, my fault. I relied only on GitHub's release view that compares by default against master and I didn't read the wiki to understand c:geo's release model.

However, I installed the latest nightly build via F-Droid (2016.04.17-NB-89f12ef) and the issue seems to be only partially fixed; I'm able to see all the images in the "Images" tab, but the entry lists only the title of the first image in the user log.

**Comment by rsudev** [comment]
@mcastellini I re-checked this issue with the original description, there it worked for me. In the log entry both image titles were listed (comma-seperated) and both images were displayed in the image tab with their respective titles.
Could you re-check, and if the behaviour persists for you, post you testcase (possibly with screen shots illustrating the issue)?
TIA

**Comment by mcastellini** [comment]
@rsudev reinstalled and refreshed, now it seems to be working fine; I checked a couple of other similar use cases and it works as well, so the issue is definitely fixed.

Just one thing: listing the images as comma-separated might not give a very clear idea of how many images are attached to a given log, even though my opinion might be biased by being used to the way geocaching.com renders logs.

**Comment by SammysHP** [comment]
We decided to use a comma separated list to reduce the necessary space. Great that it works now for you!

**Comment by rsudev** [comment]
I also consider this comma-separated list not very user friendly, so if anybody comes up with an alternative suggestion, which is also compact, feel free to communicate it in a new issue!

**Comment by Lineflyer** [comment]
Let me reopen this:
In fact this was fixed and even improved (by implementing a bullet point list) on `master`.
However maybe we overlooked that there is a regression also with the current market release. So I would like to ask if it is feasible to port this fix to `release` as well??

**Comment by pstorch** [comment]
I can try to cherry-pick into release
