### ISSUE TITLE
Unit Test instabilities on real devices

### ISSUE THREAD

**Issue by kumy** [cgeo/cgeo#6721]
Following #6692, I've set up `kumy-3` executor to run tests on real devices. I've found tests are quite instable when **screen is off**. I can force screens to be kept on, but on a long term, I don't want to damage screens...

Here is a compilation of latest errors in case someone want to cross-check / fix ;)

http://ci.cgeo.org/job/cgeo%20continuous%20integration/1706/console
```
02:51.517  Starting 406 tests on m8 - 7.1.2
02:54.085  Starting 427 tests on GT-I9305 - 4.4.4
05:37.479  
05:37.479  cgeo.geocaching.connector.ConnectorFactoryTest > testGetGeocodeFromUrl[m8 - 7.1.2] [31mFAILED [0m
05:37.486  	android.view.WindowManager$BadTokenException: Unable to add window -- window android.view.ViewRootImpl$W@2b137d4 has already been added
05:37.490  	at android.view.ViewRootImpl.setView(ViewRootImpl.java:691)
05:37.630  Tests on m8 - 7.1.2 failed: Instrumentation run failed due to 'Process crashed.'
10:20.222  :main:connectedBasicDebugAndroidTest FAILED
10:20.235  101 actionable tasks: 101 executed
```

http://ci.cgeo.org/job/cgeo%20continuous%20integration/1703/console
```
04:43.638  Starting 406 tests on m8 - 7.1.2
11:58.550  
11:58.555  cgeo.geocaching.files.GPXImporterTest > testImportOcGpx[m8 - 7.1.2] [31mFAILED [0m
11:58.563  	java.util.ConcurrentModificationException
11:58.575  	at java.util.ArrayList$Itr.next(ArrayList.java:831)
12:39.045  :main:connectedBasicDebugAndroidTest FAILED
12:39.059  101 actionable tasks: 101 executed
```

http://ci.cgeo.org/job/cgeo%20continuous%20integration/1707/console
```
02:43.222  Starting 406 tests on m8 - 7.1.2
02:48.685  Starting 427 tests on GT-I9305 - 4.4.4
08:45.417  
08:45.417  cgeo.geocaching.files.GPXImporterTest > testImportGpxWithLowercaseNames[GT-I9305 - 4.4.4] [31mFAILED [0m
08:45.421  	java.util.ConcurrentModificationException
08:45.421  	at java.util.ArrayList$ArrayListIterator.next(ArrayList.java:573)
08:56.484  
08:56.484  cgeo.geocaching.files.GPXImporterTest > testImportGpxWithWaypoints[GT-I9305 - 4.4.4] [31mFAILED [0m
08:56.485  	java.lang.AssertionError:
08:56.485  	Expected size:<5> but was:<4> in:
13:12.160  :main:connectedBasicDebugAndroidTest FAILED
```

http://ci.cgeo.org/job/cgeo%20continuous%20integration/1708/console
```
02:36.242  Starting 406 tests on m8 - 7.1.2
02:43.613  Starting 427 tests on GT-I9305 - 4.4.4
09:01.046  
09:01.046  cgeo.geocaching.files.GPXImporterTest > testImportGpxWithLowercaseNames[GT-I9305 - 4.4.4] [31mFAILED [0m
09:01.050  	java.lang.AssertionError:
09:01.050  	Expected size:<4> but was:<3> in:
09:51.962  
09:51.962  cgeo.geocaching.files.GPXImporterTest > testImportOcGpx[GT-I9305 - 4.4.4] [31mFAILED [0m
09:51.967  	java.lang.AssertionError:
09:51.967  	Expected size:<4> but was:<3> in:
10:46.585  :main:connectedBasicDebugAndroidTest FAILED
```

**Comment by kumy** [comment]
http://ci.cgeo.org/job/cgeo%20pull%20request/1080/console

```
11:19.446  cgeo.geocaching.files.GPXImporterTest > testImportOcGpx[m8 - 7.1.2] [31mFAILED [0m
11:19.447  	java.lang.AssertionError:
11:19.447  	Expected size:<4> but was:<3> in:
```

**Comment by kumy** [comment]
(Screens were on)

http://ci.cgeo.org/job/cgeo%20pull%20request/1082/consoleFull#-109812861545fc375f-a63e-468b-8450-76255356fdf9
```
08:50.382  cgeo.geocaching.files.GPXImporterTest > testImportOcGpx[GT-I9305 - 4.4.4] [31mFAILED [0m
08:50.382  	java.lang.AssertionError:
08:50.382  	Expected size:<4> but was:<3> in:
09:14.111  
09:14.111  cgeo.geocaching.files.GPXImporterTest > testImportGpxWithWaypoints[m8 - 7.1.2] [31mFAILED [0m
09:14.118  	java.util.ConcurrentModificationException
09:14.118  	at java.util.ArrayList$Itr.next(ArrayList.java:831)
11:01.169  :main:connectedBasicDebugAndroidTest FAILED
```

**Comment by kumy** [comment]
Does someone have skills to fix those issues?

Are they reproducible for you?

**Comment by pstorch** [comment]
Hmm, when I run `./gradlew testDebug` with my real device, the only tests which fail are the one where I don't have configured a key: WatchdogTest.testOpenCach... and OkapiClientTest.testGetOCCache.

**Comment by kumy** [comment]
@pstorch may you please try with your screen turned off?

**Comment by pstorch** [comment]
@kumy same result

**Comment by kumy** [comment]
Thanks. strange as it happen on both devices I own.
I have to dig deeper...

**Comment by rsudev** [comment]
I thought it might be related to the static maps download message, which would be missing if that setting was turned off on your device. But than the other gpx import tests should fail as well...
Did you check which message is missing?

**Comment by kumy** [comment]
Running the tests from Android studio (current master) with screen off
I can have it crash on 2 tests.
here are the logcat parts and full stack trace

**testImportGpxWithLowercaseNames**
```
I/TestRunner( 1874): started: testImportGpxWithLowercaseNames(cgeo.geocaching.files.GPXImporterTest)
I/TestRunner( 1874): failed: testImportGpxWithLowercaseNames(cgeo.geocaching.files.GPXImporterTest)
I/TestRunner( 1874): 	at cgeo.geocaching.files.GPXImporterTest.assertImportStepMessages(GPXImporterTest.java:161)
I/TestRunner( 1874): 	at cgeo.geocaching.files.GPXImporterTest.testImportGpxWithLowercaseNames(GPXImporterTest.java:149)
I/TestRunner( 1874): finished: testImportGpxWithLowercaseNames(cgeo.geocaching.files.GPXImporterTest)
```

```
java.util.ConcurrentModificationException
at java.util.ArrayList$ArrayListIterator.next(ArrayList.java:573)
at org.assertj.core.presentation.StandardRepresentation.format(StandardRepresentation.java:367)
at org.assertj.core.presentation.StandardRepresentation.singleLineFormat(StandardRepresentation.java:390)
at org.assertj.core.presentation.StandardRepresentation.smartFormat(StandardRepresentation.java:404)
at org.assertj.core.presentation.StandardRepresentation.toStringOf(StandardRepresentation.java:137)
at org.assertj.core.error.MessageFormatter.asText(MessageFormatter.java:77)
at org.assertj.core.error.MessageFormatter.format(MessageFormatter.java:68)
at org.assertj.core.error.MessageFormatter.format(MessageFormatter.java:61)
at org.assertj.core.error.BasicErrorMessageFactory.create(BasicErrorMessageFactory.java:110)
at org.assertj.core.internal.Failures.failure(Failures.java:116)
at org.assertj.core.internal.CommonValidations.checkSizes(CommonValidations.java:119)
at org.assertj.core.internal.Iterables.assertHasSize(Iterables.java:173)
at org.assertj.core.api.AbstractIterableAssert.hasSize(AbstractIterableAssert.java:160)
at cgeo.geocaching.files.GPXImporterTest.assertImportStepMessages(GPXImporterTest.java:161)
at cgeo.geocaching.files.GPXImporterTest.testImportGpxWithLowercaseNames(GPXImporterTest.java:149)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:515)
at android.test.InstrumentationTestCase.runMethod(InstrumentationTestCase.java:214)
at android.test.InstrumentationTestCase.runTest(InstrumentationTestCase.java:199)
at junit.framework.TestCase.runBare(TestCase.java:134)
at junit.framework.TestResult$1.protect(TestResult.java:115)
at android.support.test.internal.runner.junit3.AndroidTestResult.runProtected(AndroidTestResult.java:77)
at junit.framework.TestResult.run(TestResult.java:118)
at android.support.test.internal.runner.junit3.AndroidTestResult.run(AndroidTestResult.java:55)
at junit.framework.TestCase.run(TestCase.java:124)
at android.support.test.internal.runner.junit3.NonLeakyTestSuite$NonLeakyTest.run(NonLeakyTestSuite.java:63)
at junit.framework.TestSuite.runTest(TestSuite.java:243)
at junit.framework.TestSuite.run(TestSuite.java:238)
at android.support.test.internal.runner.junit3.DelegatingTestSuite.run(DelegatingTestSuite.java:103)
at android.support.test.internal.runner.junit3.AndroidTestSuite.run(AndroidTestSuite.java:69)
at android.support.test.internal.runner.junit3.JUnit38ClassRunner.run(JUnit38ClassRunner.java:103)
at org.junit.runners.Suite.runChild(Suite.java:128)
at org.junit.runners.Suite.runChild(Suite.java:27)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
at android.support.test.internal.runner.TestExecutor.execute(TestExecutor.java:59)
at android.support.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:262)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1701)
```


**testImportOcGpx**
```
I/TestRunner( 1874): failed: testImportOcGpx(cgeo.geocaching.files.GPXImporterTest)
I/TestRunner( 1874): 	at cgeo.geocaching.files.GPXImporterTest.testImportOcGpx(GPXImporterTest.java:100)
I/TestRunner( 1874): finished: testImportOcGpx(cgeo.geocaching.files.GPXImporterTest)
```


```
java.util.ConcurrentModificationException
at java.util.ArrayList$ArrayListIterator.next(ArrayList.java:573)
at org.assertj.core.presentation.StandardRepresentation.format(StandardRepresentation.java:367)
at org.assertj.core.presentation.StandardRepresentation.singleLineFormat(StandardRepresentation.java:390)
at org.assertj.core.presentation.StandardRepresentation.smartFormat(StandardRepresentation.java:404)
at org.assertj.core.presentation.StandardRepresentation.toStringOf(StandardRepresentation.java:137)
at org.assertj.core.error.MessageFormatter.asText(MessageFormatter.java:77)
at org.assertj.core.error.MessageFormatter.format(MessageFormatter.java:68)
at org.assertj.core.error.MessageFormatter.format(MessageFormatter.java:61)
at org.assertj.core.error.BasicErrorMessageFactory.create(BasicErrorMessageFactory.java:110)
at org.assertj.core.internal.Failures.failure(Failures.java:116)
at org.assertj.core.internal.CommonValidations.checkSizes(CommonValidations.java:119)
at org.assertj.core.internal.Iterables.assertHasSize(Iterables.java:173)
at org.assertj.core.api.AbstractIterableAssert.hasSize(AbstractIterableAssert.java:160)
at cgeo.geocaching.files.GPXImporterTest.testImportOcGpx(GPXImporterTest.java:100)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:515)
at android.test.InstrumentationTestCase.runMethod(InstrumentationTestCase.java:214)
at android.test.InstrumentationTestCase.runTest(InstrumentationTestCase.java:199)
at junit.framework.TestCase.runBare(TestCase.java:134)
at junit.framework.TestResult$1.protect(TestResult.java:115)
at android.support.test.internal.runner.junit3.AndroidTestResult.runProtected(AndroidTestResult.java:77)
at junit.framework.TestResult.run(TestResult.java:118)
at android.support.test.internal.runner.junit3.AndroidTestResult.run(AndroidTestResult.java:55)
at junit.framework.TestCase.run(TestCase.java:124)
at android.support.test.internal.runner.junit3.NonLeakyTestSuite$NonLeakyTest.run(NonLeakyTestSuite.java:63)
at junit.framework.TestSuite.runTest(TestSuite.java:243)
at junit.framework.TestSuite.run(TestSuite.java:238)
at android.support.test.internal.runner.junit3.DelegatingTestSuite.run(DelegatingTestSuite.java:103)
at android.support.test.internal.runner.junit3.AndroidTestSuite.run(AndroidTestSuite.java:69)
at android.support.test.internal.runner.junit3.JUnit38ClassRunner.run(JUnit38ClassRunner.java:103)
at org.junit.runners.Suite.runChild(Suite.java:128)
at org.junit.runners.Suite.runChild(Suite.java:27)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
at android.support.test.internal.runner.TestExecutor.execute(TestExecutor.java:59)
at android.support.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:262)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1701)
```

**Comment by kumy** [comment]
Running the failing tests alone doesn't cause any trouble

**Comment by pstorch** [comment]
Also via AS, I get the same result:
![selection_022](https://user-images.githubusercontent.com/5598124/30252107-abd8d014-966c-11e7-9ee4-1063fa57084c.png)

**Comment by kumy** [comment]
Differences could be related to the way the application is configured. For unit tests, a `cgeo.geocaching_preferences.xml` is pushed before the application is installed which configure the settings. The copy I own came from `master` executor (the problem should exists there too?). And last thing, I don't know how to generate this file, and which values are good for testing.

**Comment by pstorch** [comment]
I've never changed or used this file. I just copied it to the main directory and changed username/password to my own. Testresult is still the same.

**Comment by kumy** [comment]
Latest jobs run "almost" fine and I didn't changed anything...

| Job | Status |
|------|----------|
| [#1086](http://ci.cgeo.org/job/cgeo%20pull%20request/1086/) | OK |
| [#1087](http://ci.cgeo.org/job/cgeo%20pull%20request/1087/) | *KO* |
| [#1088](http://ci.cgeo.org/job/cgeo%20pull%20request/1088/) | OK |
| [#1089](http://ci.cgeo.org/job/cgeo%20pull%20request/1089/) | OK |
| [#1090](http://ci.cgeo.org/job/cgeo%20pull%20request/1090/) | KO |

http://ci.cgeo.org/job/cgeo%20pull%20request/

**Comment by pstorch** [comment]
Interesting. Maybe your machine is more or less busy.

**Comment by kumy** [comment]
I just added adb sequence to the script to power on and off the screen for each builds.

**Comment by kumy** [comment]
http://ci.cgeo.org/job/cgeo%20continuous%20integration%20-%20manual%20build/176/console

```
02:23.774  :main:connectedBasicDebugAndroidTest
02:36.448  Starting 406 tests on m8 - 7.1.2
02:39.757  Starting 427 tests on GT-I9305 - 4.4.4

06:14.494  
06:14.494  cgeo.geocaching.connector.gc.GCParserTest > testEditModifiedCoordinates[GT-I9305 - 4.4.4] [31mFAILED [0m
06:14.494  	org.junit.ComparisonFailure: expected:<[fals]e> but was:<[tru]e>
06:14.499  	at java.lang.reflect.Constructor.constructNative(Native Method)
```

**Comment by kumy** [comment]
http://ci.cgeo.org/job/cgeo%20pull%20request/1097/console

```
02:16.878  :main:connectedBasicDebugAndroidTest
02:29.659  Starting 406 tests on m8 - 7.1.2
02:36.364  Starting 427 tests on GT-I9305 - 4.4.4

06:04.103  
06:04.103  cgeo.geocaching.connector.gc.GCParserTest > testEditModifiedCoordinates[m8 - 7.1.2] [31mFAILED [0m
06:04.109  	org.junit.ComparisonFailure: expected:<[fals]e> but was:<[tru]e>
06:04.109  	at java.lang.reflect.Constructor.newInstance0(Native Method)
```

**Comment by kumy** [comment]
http://ci.cgeo.org/job/cgeo%20pull%20request/1099/console

```
05:02.801  cgeo.geocaching.connector.ConnectorFactoryTest > testGetGeocodeFromUrl[m8 - 7.1.2] [31mFAILED [0m
05:02.801  	org.junit.ComparisonFailure: expected:<"OC10F41"> but was:<null>
05:02.801  	at java.lang.reflect.Constructor.newInstance0(Native Method)
05:04.954  
05:04.954  cgeo.geocaching.connector.ConnectorFactoryTest > testGetGeocodeFromUrl[GT-I9305 - 4.4.4] [31mFAILED [0m
05:04.960  	org.junit.ComparisonFailure: expected:<"OC10F41"> but was:<null>
05:04.960  	at java.lang.reflect.Constructor.constructNative(Native Method)
10:44.849  
10:44.849  cgeo.geocaching.files.GPXImporterTest > testImportOcGpx[m8 - 7.1.2] [31mFAILED [0m
10:44.849  	java.lang.AssertionError:
10:44.849  	Expected size:<4> but was:<3> in:
11:26.592  :main:connectedBasicDebugAndroidTest FAILED
```

**Comment by pstorch** [comment]
@kumy do you run the tests on two devices in parallel?
```
22:56:30  Starting 406 tests on m8 - 7.1.2
22:56:31  Starting 427 tests on GT-I9305 - 4.4.4
```
I'm wondering about the different number of tests per device. What happens if you only use 1 device?

**Comment by kumy** [comment]
@pstorch Yes they run in parallel. There was only one device before, it was: `m8 - 7.1.2`. I'll unplug it for some days and leave only `GT-I9305 - 4.4.4` (I have never tested it alone...)

Regarding number of tests, there is also some informations in https://github.com/cgeo/cgeo/issues/6692#issuecomment-324106776

**Comment by kumy** [comment]
Strange, with `GT-I9305 - 4.4.4` alone, there is now 425 tests launched instead of 427.

http://ci.cgeo.org/job/cgeo%20pull%20request/1100/console

**Comment by pstorch** [comment]
Maybe it's because they are from two different PRs. This one has 2 tests less.

**Comment by pstorch** [comment]
Tests were good for this PR. Try another one? 
Then what is different with the m8? It has a quite recent Android version. Much newer than the other one.

**Comment by kumy** [comment]
Let's build #1101 end, then switch phone and run the same test

**Comment by kumy** [comment]
On job `cgeo pull request`: from job 1057 to 1001

`m8 - 7.1.2` has failed 23 times | Count
------------------------|---------
connector.gc.GCParserTest > testEditModifiedCoordinates    | 2
connector.ConnectorFactoryTest > testGetGeocodeFromUrl | 5
connector.gc.GCConnectorTest > testGetViewport                 | 3
files.GPXImporterTest > testImportGpxWithLowercaseNames | 1
files.GPXImporterTest > testImportGpxWithWaypoints           | 4
files.GPXImporterTest > testImportOcGpx                              | 8

`GT-I9305 - 4.4.4` has failed 10 times | Count
------------------------|---------
connector.gc.GCParserTest > testEditModifiedCoordinates | 2
connector.ConnectorFactoryTest > testGetGeocodeFromUrl | 1
files.GPXImporterTest > testImportGpxWithLowercaseNames | 3
files.GPXImporterTest > testImportOcGpx | 4


----------------------------------

On job `cgeo continuous integration`: from job 1600 to 1711

`m8 - 7.1.2` has failed 9 times | Count
------------------------|---------
files.GPXImporterTest > testImportGpxWithWaypoints | 1
files.GPXImporterTest > testImportOcGpx | 4
connector.gc.GCConnectorTest > testGetViewport | 2
connector.ConnectorFactoryTest > testGetGeocodeFromUrl | 1
files.GPXImporterTest > testImportGpxAttachment | 1


`GT-I9305 - 4.4.4` has failed 6 times | Count
------------------------|---------
files.GPXImporterTest > testImportGpxWithLowercaseNames | 3
files.GPXImporterTest > testImportGpxWithWaypoints | 1
files.GPXImporterTest > testImportOcGpx | 2

**Comment by pstorch** [comment]
Regarding `GPXImporterTest.testImportOcGpx()`: it expects 4 messages from the `importStepHandler`. The test somtimes fails because it has only 3 messages. There is one optional message `GPXImporter.IMPORT_STEP_STORE_STATIC_MAPS` according to the user preferences. Do you have a `cgeo.geocaching_preferences.xml` file where loading of static maps is disabled?

**Comment by kumy** [comment]
@pstorch I'll mail you the currently used file.

```
$ grep map cgeo.geocaching_preferences.xml
<map>
    <boolean name="navigationRmaps" value="true" />
    <boolean name="mapsforgeScaleText" value="true" />
    <boolean name="map_direction" value="true" />
    <string name="mapsource">658963267</string>
    <boolean name="offlinemaps" value="true" />
    <boolean name="navigationOruxmaps" value="true" />
    <int name="livemapstrategy" value="3" />
    <boolean name="maptrail" value="false" />
    <boolean name="offlinewpmaps" value="true" />
</map>
```

**Comment by pstorch** [comment]
@kumy as a first try I've put your preferences file into the `main` subdirectory.
I got this result:
```
[100%] /data/data/cgeo.geocaching/shared_prefs/cgeo.geocaching_preferences.xml
adb: error: failed to copy 'cgeo.geocaching_preferences.xml' to '/data/data/cgeo.geocaching/shared_prefs/cgeo.geocaching_preferences.xml': remote couldn't create file: Permission denied
cgeo.geocaching_preferences.xml: 0 files pushed. 0.9 MB/s (4613 bytes in 0.005s)
Process 'command '/home/peter/Android/Sdk/platform-tools/adb'' finished with non-zero exit value 1
Starting 414 tests on ONEPLUS A3003 - 7.1.1
```
Looks like the copy failed, because there is already my current preferences file. Maybe I have to uninstall the app manually first and try again. I'll try again tomorrow. 
I only have 414 tests, because I miss some OC keys. I only have the one for de.

**Comment by kumy** [comment]
@pstorch I've send you OC keys privately.

> adb: error: failed to copy 'cgeo.geocaching_preferences.xml' to '/data/data/cgeo.geocaching/shared_prefs/cgeo.geocaching_preferences.xml': remote couldn't create file: Permission denied

I also got this error, IIRC I've fixed that using [`adb root && adb remount`](https://github.com/cgeo/cgeo-executor/blob/real_devices/restart-emulator.sh#L16-L17)

**Comment by pstorch** [comment]
@kumy that didn't work for me:
> I also got this error, IIRC I've fixed that using adb root && adb remount

But I could solve it with these two steps:
```
adb push main/cgeo.geocaching_preferences.xml /sdcard/cgeo.geocaching_preferences.xml
adb -d shell "run-as cgeo.geocaching cp /sdcard/cgeo.geocaching_preferences.xml /data/data/cgeo.geocaching/shared_prefs/cgeo.geocaching_preferences.xml"
```

I can change it in the `main/build.gradle` file as well, if it is relevant for others.

But in the end it didn't change anything. My `./gradlew testDebug` has still the same result.
```
Starting 414 tests on ONEPLUS A3003 - 7.1.1

BUILD SUCCESSFUL in 6m 31s
105 actionable tasks: 39 executed, 66 up-to-date
```

**Comment by pstorch** [comment]
In don't get the `GPXImporterTest.testImportOcGpx()` test to fail in my PR #6739.


In the other PR I got this error: 
http://ci.cgeo.org/job/cgeo%20pull%20request/1111/console
```
21:28:03  cgeo.geocaching.connector.gc.GCConnectorTest > testGetViewport[m8 - 7.1.2] [31mFAILED [0m
21:28:03  	android.view.WindowManager$BadTokenException: Unable to add window -- window android.view.ViewRootImpl$W@d7e7577 has already been added
21:28:03  	at android.view.ViewRootImpl.setView(ViewRootImpl.java:691)
21:28:03  Tests on m8 - 7.1.2 failed: Instrumentation run failed due to 'Process crashed.'
```

The last line about the instrumentation failed because of a process crash sounds very scary. What can have caused this?

**Comment by kumy** [comment]
Hum... I'll try to move stuff on another computer ASAP. I just remember I got problems this summer to root my new phone, when it worked fine on another computer. (Android <==> Intel Nuc issue ?)

**Comment by kumy** [comment]
Same issue on another computer. Fresh docker container built. On HTC m8.

http://ci.cgeo.org/job/cgeo%20continuous%20integration%20-%20manual%20build/178/console

```
00:52:49  Starting 406 tests on m8 - 7.1.2

00:59:35  
00:59:35  cgeo.geocaching.files.GPXImporterTest > testImportOcGpx[m8 - 7.1.2] [31mFAILED [0m
00:59:35  	java.util.ConcurrentModificationException
00:59:35  	at java.util.ArrayList$Itr.next(ArrayList.java:831)

01:00:18  :main:connectedBasicDebugAndroidTest FAILED
```

**Comment by pstorch** [comment]
Another strange failure:

http://ci.cgeo.org/job/cgeo%20pull%20request/1120/console
```
23:30:15  cgeo.geocaching.connector.gc.GCConnectorTest > testGetViewport[GT-I9305 - 4.4.4] [31mFAILED [0m
23:30:15  Test failed to run to completion. Reason: 'Test run failed to complete. Expected 427 tests, received 64'. Check device logcat for details
23:30:15  Tests on GT-I9305 - 4.4.4 failed: Test run failed to complete. Expected 427 tests, received 64
23:36:17  [no message defined]
23:36:17  com.android.ddmlib.AdbCommandRejectedException: device '430091ee9675c05b' not found
23:36:17  	at com.android.ddmlib.AdbHelper.setDevice(AdbHelper.java:862)
```

Device not found?

**Comment by kumy** [comment]
I've rebuild everything from scratch, using emulators, on an external server. `cgeo-1` and `cgeo-2` executors seems stable. Error disappeared there...

I'm working on providing executors, which will run the tests on multiple android SDK version at same time.

Closing here.
