### ISSUE TITLE
Logs View Scrollbar is buggy 

### ISSUE THREAD

**Issue by fm-sys** [cgeo/cgeo#8406]
You can press the button in the right bar to scroll through the logs faster.  That's a good thing.

But if you get to the border bar during normal scrolling, the above mentioned button jumps to the corresponding position on this scrollbar.

This is quite buggy, because you always lose the position you were reading.
So only accept clicks on the scrollbutton, not on the hole scrollbar.

Many thanks and best regards

**Comment by Lineflyer** [comment]
AFAIR the fastscroll bar should disappear a few moments after having used the function and should therefore not affect normal scrolling, or am I wrong or we have a bug of the bar being constantly shown on some devices?

**Comment by fm-sys** [comment]
![VID_20200604_235050](https://user-images.githubusercontent.com/64581222/83837171-fc669100-a6f5-11ea-8ecd-0e06ee1fbb64.gif)

That's what I mean...

**Comment by MagpieFourtyTwo** [comment]
Same over here:
- you scroll a bit ...
- scroll bar disappears
- you tap on a log to just "grab" it, in order to scroll down a few lines
- if your tap was a little bit too far to the right, log list will immediately jump to the corresponding position of the entire list (i. e. tap at half height of screen, log list will jump to the log at 50 % of log list), no matter if scroll bar was visible before or if you additionally move your finger.

This even happens when tapping way left of the scroll bar region (about three to four times of the scroll bar width).

This happens to both of our devices, i. e. different hardware and android versions.

**Comment by MagpieFourtyTwo** [comment]
Sorry, but AFAI understood the TO, he reported a different problem than the one you fixed.  ;)
At least his (and mine, BTW, too ;) ) problem was not a non disappearing scroll bar, but an unexpected jump of the fast scroll bar ...

Perhaps I may try to explain in another way:

- you are in a long list of caches (or logs, doesn't matter, the problem appears to be the same)
- you start at the top and want to read one after the other, so you tap and scroll down a bit (i. e. swipe your finger upwards)
- this works perfectly fine *as long as your finger tap lands somewhere in the (horizontal) center of the screen*
- but as this is pretty uncomfortable, and as add. you don't want your finger to cover the text you're reading, your finger unconsciously taps a little bit more to the right each time you want to scroll down a few(!) logs (or caches)
- so eventually the moment comes, when your finger tap lands *too* close to the right edge of the screen ... tap takes place ... BTW: there is still no quick scroll bar visible yet ... but as soon as you start to swipe your finger upwards ... **\*BAM*** the list jumps via quick scroll down several dozens to hundreds entries ... i. e. relative to the position where your finger is ... oops.
- would be bad enough that you have to scroll up again all the way now, but mayor pity is: you lost your reading position completely ...  :/

So, his approach / proposal was (and I would like to second that), to *not* accept any touch at any (vertical) position on the quick scroll bar (resp. on the very right edge of the display) to let the list jump there immediately, but only accept "grabbing" the list position marker (the small part of the quick scroll bar with the higher opaqueness, which shows the current position in the list) to consciously pull it down (or up, of course) for a fast scroll. And every other tap, even if on the fast scroll bar's lower opaqueness parts, may just be understood as "normal" scroll moves ...

Hope I was able to describe it more understandable ...

**Comment by moving-bits** [comment]
I stumble upon this behavior myself from time to time, and I know how frustrating it can be. Hypothetically I would see (at least) three ways to mitigate the behavior:
- restrict the dragging to the highlighted part of the slider by configuration;
- make the touch area smaller, making it less probable to hit the fast scroll slider accidently;
- detect the touch position, and calculate whether it's been inside or outside the hightlighted part of the slider;
- ...

Alas, fastscroll itself is a built-in Android functionality applied to the cache list view, and is not really customizable. I've found no way to do any of the things mentioned above, leaving the options of implementing my own fastscroll solution (which I would like to avoid) or trying to tweak the existing one.

I started with the latter. The mitigation works by reducing the amount of time fast scroll is active. As soon as you stop scrolling for at least a second, fast scroll is disabled. (Fast scroll bar being non visible then is just a consequence of it, not the actual intended goal.) Have you tried if this brings some relief?

OTOH I'd be happy to implement a different solution. Do you have suggestions for when to deactive / activate fast scroll? (This could be dependent on time or on [scroll state](https://developer.android.com/reference/android/widget/AbsListView.OnScrollListener).)

**Comment by fm-sys** [comment]
I hadn't time to test the PR, but this should help minimize the harm... ;-) Thank you! 

But maybe activate fast scroll only when the user performs a fling, not on slow scrolling... Because if you are scrolling slowly, you don't need the fast scroll functionality. 
The only thing is, that when scrolling slowly you wouldn't see the scroll position in the list. Or is it possible to display the normal scroll position indicator when fastscroll is disabled... But this mixture would would be too confusing, wouldn't it?

**Comment by MagpieFourtyTwo** [comment]
> restrict the dragging to the highlighted part of the slider by configuration;

This would of course be the very best (and most intuitive) solution.

> make the touch area smaller, making it less probable to hit the fast scroll slider accidently;

Smaller = less wide (horizontally)?  Could probably reduce the pain, but does not really solve the problem.
Moreover it would make it harder to use fast scroll intentionally.
And, BTW, things will get even worse with "waterfall edges".

> detect the touch position, and calculate whether it's been inside or outside the hightlighted part of the slider;

Sounds a little bit too effortful to me (thinking of screen density and stuff to be considered, the risk of adding bug potential appears to be pretty high to me), esp. for just a "comfort function", which is most probably seldom used anyway: At least in the logs list I would consider it as not needed anyway, cause there usually are just about 10 pages or so, which can even be scrolled completely by 3 to 4 fast wipes ... so perhaps easiest solution for the logs page would be, to deactivate fast scroll completely (as I can't imagine any scenario, where I would need it in the logs, anyway).

As for the cache lists: Over there the pain is not that big (IMHO), cause the "lost" position in the list can be restored more easy (cause they are sorted) - so perhaps there it could really be sufficient, to make the width of the fast scroll region narrower ... if "restricting the dragging to the highlighted part of the slider by configuration" is not possible.

> Alas, fastscroll itself is a built-in Android functionality applied to the cache list view, and is not really customizable.

Yep, kind of expected s/th like that ...  :/

> The mitigation works by reducing the amount of time fast scroll is active.

This would not change anything at all, cause the (fast) scroll bar is not active before you touch the fast scroll region anyway, thus decreasing the time it will stay active afterwards makes no difference. 

> OTOH I'd be happy to implement a different solution. Do you have suggestions for when to deactive / activate fast scroll? (This could be dependent on time or on scroll state.)

Not yet ... but will think about it ...

**Comment by MagpieFourtyTwo** [comment]
Ah, just stumbled upon the way, windows implements scrolling:
- one click on the scroll bar: go up/down one page
- long click on the scroll bar: go up/down in 1 page steps,
   but just as long as the mouse does not move

So, perhaps the movement (resp. stop) of the finger can be a criterion for deactivating (or activating) fast scroll?
And perhaps there can be a pause between pages ...? So one can at least realize what is happening ...?

**Comment by moving-bits** [comment]
> But maybe activate fast scroll only when the user performs a fling, not on slow scrolling... Because if you are scrolling slowly, you don't need the fast scroll functionality.

Sounds like a possible workaround to me.
@MagpieFourtyTwo:  What do you think?

> The only thing is, that when scrolling slowly you wouldn't see the scroll position in the list. Or is it possible to display the normal scroll position indicator when fastscroll is disabled... But this mixture would would be too confusing, wouldn't it?

When fastscroll is disabled you see the very thin position indicator. Fast scroll indicator is much wider than that.

**Comment by moving-bits** [comment]
> > make the touch area smaller, making it less probable to hit the fast scroll slider accidently;
> 
> Smaller = less wide (horizontally)? Could probably reduce the pain, but does not really solve the problem.

yes & yes

> Moreover it would make it harder to use fast scroll intentionally.
> And, BTW, things will get even worse with "waterfall edges".

ah, you're right

> At least in the logs list I would consider it as not needed anyway, cause there usually are just about 10 pages or so, 

You're probably right, although it depends a bit on the log text length.

> As for the cache lists: Over there the pain is not that big (IMHO), cause the "lost" position in the list can be restored more easy (cause they are sorted)

Here I disagree. Yes, it may be easier to find the position where I have been (depending on the current sort mode), but it's still pretty annoying if I have to scroll several hundred entries.

> so perhaps there it could really be sufficient, to make the width of the fast scroll region narrower ... if "restricting the dragging to the highlighted part of the slider by configuration" is not possible.

sadly neither is possible with built-in fastscroll

> > The mitigation works by reducing the amount of time fast scroll is active.
> 
> This would not change anything at all, cause the (fast) scroll bar is not active before you touch the fast scroll region anyway, thus decreasing the time it will stay active afterwards makes no difference.

There is a subtile difference: After fastscroll is deactivated after 1s of not scrolling, you can tap somewhere down on the (now thin) scrollbar, and position will *not* jump to that position.

**Comment by moving-bits** [comment]
(Reopen to make tracking easier)

**Comment by moving-bits** [comment]
Combining the last posts a possible solution could be like this:
- stay with time-based deactivating fast scroll (as implemented this week),
- but re-activate fastscroll only on fling scroll mode, not on regular scroll mode
- additionally: disable fastscroll by default (so that it only gets activated on first fling)

**Comment by moving-bits** [comment]
> Ah, just stumbled upon the way, windows implements scrolling:
> * one click on the scroll bar: go up/down one page
> * long click on the scroll bar: go up/down in 1 page steps, but just as long as the mouse does not move
> 
> So, perhaps the movement (resp. stop) of the finger can be a criterion for deactivating (or activating) fast scroll?
> And perhaps there can be a pause between pages ...? So one can at least realize what is happening ...?

This could be a possible implementation for an individually programmed scrollbar.
Problem with the built-in is, that you don't get triggered by each click, but only on the results (meaning: you don't get notified for "clicked on the scrollbar at position x/y" but for "moved the visible window to entry number x".

So if we would try to implement the scenario described above, we would need to revert an already done movement and scroll back to some earlier position, which would lead to a bad user experience IMHO.

**Comment by MagpieFourtyTwo** [comment]
Yep, agreed. Ok, so Windows' implementation is out.

[fastscroll in sorted lists only]
> it's still pretty annoying if I have to scroll several hundred entries.

Yes, of course it is, but if we only have the choice between two evil, I would go with the less painful.  ;)

> > But maybe activate fast scroll only when the user performs a fling, not on slow scrolling... Because if you are scrolling slowly, you don't need the fast scroll functionality.

> Sounds like a possible workaround to me.
> @MagpieFourtyTwo: What do you think?

Seconded.

BTW: While checking various scroll bars, I stumbled upon the one in the system settings list - while slow scrolling it is obviously completely out of sync - how come?

**Comment by moving-bits** [comment]
I've created a tryout version implementing the proposal above, see #8590. Will merge after tests have completed, so it should be in the nightlies then.

**Comment by moving-bits** [comment]
> BTW: While checking various scroll bars, I stumbled upon the one in the system settings list - while slow scrolling it is obviously completely out of sync - how come?

It normally shows the letter of the first entry on the page (except when coming to the end of the list).

If that's not the desired behavior: Can you describe how it should behave? Then I will see if I can fix the implementation.

**Comment by MagpieFourtyTwo** [comment]
The letter stuff is well known and works. I just meant the "normal" i. e. slow scroll:
You scroll down half a page and the scroll position marker goes down half a page, too - which is obviously wrong, as the list is way longer than one page. Then, if you (slowly) scroll down more than a page, the scroll position marker leaves the page at the bottom ...

Concerning the tryout-Version: Following [commits](https://github.com/cgeo/cgeo/commits/master) [aec4039](https://github.com/cgeo/cgeo/commit/aec4039c58bf4486e2f5d0555a1eee5262c85b26) seems to already be merged to master - but I can not see any difference (nightly 2020.07.07-NB-9987256) - or do I miss something?

**Comment by moving-bits** [comment]
> The letter stuff is well known and works. I just meant the "normal" i. e. slow scroll:
> You scroll down half a page and the scroll position marker goes down half a page, too - which is obviously wrong, as the list is way longer than one page. Then, if you (slowly) scroll down more than a page, the scroll position marker leaves the page at the bottom ...

Fixed this one with #8592 - there was one method implementation missing.

**Comment by moving-bits** [comment]
> Concerning the tryout-Version: Following [commits](https://github.com/cgeo/cgeo/commits/master) [aec4039](https://github.com/cgeo/cgeo/commit/aec4039c58bf4486e2f5d0555a1eee5262c85b26) seems to already be merged to master - but I can not see any difference (nightly 2020.07.07-NB-9987256) - or do I miss something?

Seems that every scroll movement ends up in fling mode, if you do not actively bring the movement to a complete halt, so let's add a minimum required movement in fling mode as prerequisite to activate fastscroll move (see #8593).

**Comment by fm-sys** [comment]
I've tested the current nightly and everything works as it should. I just can't tell if the minimum fling distance is too high or just right, because I only tested it in emulator. Here we maybe need feedback...

The difficulty in applying the same fix to the logview is that, if I understand the PR correctly, you have to fling a certain number of entries to enable fastscroll, but the length of the log entries is always different, so we need something else to calculate the fling distance in logview.

**Comment by moving-bits** [comment]
> I've tested the current nightly and everything works as it should. I just can't tell if the minimum fling distance is too high or just right, because I only tested it in emulator. Here we maybe need feedback...

@fm-sys Thanks for cross-checking. Currently I'm using a min distance of 10, but as the "automatic fling" after manual scrolling probably only spans one or two entries we can set a lower limit. Maybe three would suffice?

> The difficulty in applying the same fix to the logview is that, if I understand the PR correctly, you have to fling a certain number of entries to enable fastscroll, but the length of the log entries is always different, so we need something else to calculate the fling distance in logview.

There's no info on "pixel" etc. provided, even the number of entries are to calculated indirectly.
But setting a lower "min fling distance" as described above might help already.

**Comment by MagpieFourtyTwo** [comment]
Sorry, but I still see no difference (on Huawei P30 Pro) ... :/
Version: 2020.07.09-NB-0c91fff

**Comment by Lineflyer** [comment]
I did not follow allow the posts and changes here, but I read somehow that the changes done are for cache lists but not or log view. Am I right @moving-bits ?

**Comment by moving-bits** [comment]
Yes, current trial version is implemented in cache list only for now.
As soon as we have a reasonably working solution I will do the next step (extract and generalize needed modification, and decide to which views to apply).

**Comment by MagpieFourtyTwo** [comment]
Ok - thanks for putting me back in focus.
So, I tested with cache list ... and I really like the <sort criterion> bubble, which is really great, when sorted by log date. ;)
But did not get a clear view of the way mode switching may work ... cause once fast scroll mode is activated, it seems to take a little bit too long until "slow scroll" is back ... how long is the timeout?  Or what are the conditions for the switch back?
Most of the times I would have said, it's a timeout of about three seconds after scroll bar faded away. But once in a while fast scroll was activated immediately after the first touch ... even if there was a minute since the last tap ...

IMHO it would be more comprehensible and easier to handle for the user, when fast scroll will be deactivated (resp. mode is switched back to "normal" scroll) as soon as the fast scroll bar vanishes ...

As for the problem to estimate a flip (resp it's speed) on log page: As said before (AFAIR) I would remove fast scroll in log view page completely, as the amount of logs is limited anyway and even in "slow scroll" mode both ends of the list can easily be reached. Thus the benefit of "fast scroll" weighs much less over there than its damage. Just my 0.02 $.

**Comment by fm-sys** [comment]
> on log page: As said before (AFAIR) I would remove fast scroll in log view page completely, as the amount of logs is limited anyway and even in "slow scroll" mode both ends of the list can easily be reached. Thus the benefit of "fast scroll" weighs much less over there than its damage.
 
I never used fast scroll at the log view page too. So I would agree to remove fast scroll completely

**Comment by Lineflyer** [comment]
> So, I tested with cache list ... and I really like the <sort criterion> bubble, which is really great, when sorted by log date. ;)

I also like that thumb/bubble. Only the background color is somehow ugly as it does not repeat any othe color we use. How about that orange as in the new logo map background?

**Comment by Lineflyer** [comment]
> on log page: As said before (AFAIR) I would remove fast scroll in log view page completely, as the amount of logs is limited anyway and even in "slow scroll" mode both ends of the list can easily be reached. Thus the benefit of "fast scroll" weighs much less over there than its damage.
> 
> 
> I never used fast scroll at the log view page too. So I would agree to remove fast scroll completely

Well, from some geocaching platforms or from imported GPX the log lists can be much longer. 
So I would vote for keeping it, if it works smooth after applying the same changes as to list view it shouldnt be a problem to keep it.

**Comment by MagpieFourtyTwo** [comment]
Orange with black background (dark mode) would be a shocker, esp. at night. ;)

So I would prefer more decent colors like in the header bar (over here: some dark and light grey).

**Comment by moving-bits** [comment]
> I also like that thumb/bubble. Only the background color is somehow ugly as it does not repeat any othe color we use. How about that orange as in the new logo map background?

The color Android uses for the fastscroll bubble is internally called `colorAccent`, which we haven't set in our theme, therefore falls back to Android standard accent color. This is the same color we have in progress bars and button texts (if not overridden explicitly by a specific style).

I would be happy to set this color to our new logo's orange tone, to give c:geo a bit more of branding which still keeping to Android Material theme standards.

**Comment by moving-bits** [comment]
It would look like this:

![image](https://user-images.githubusercontent.com/3754370/87189326-c027e100-c2f0-11ea-9722-9e166f4e1b3f.png)

**Comment by moving-bits** [comment]
> But did not get a clear view of the way mode switching may work ... cause once fast scroll mode is activated, it seems to take a little bit too long until "slow scroll" is back ... how long is the timeout? Or what are the conditions for the switch back?

Current setting is:

- enabling fast scroll:
  - scroll state == FLING
  - and: must have flinged for more than two items (*) (which may vary in length)
    (\* meaning: the position number of the first visible item on the view must have changed by more than two up or down)
- disabling fast scroll:
  - scroll state == IDLE: set timer for in 1s
  - when timer reached: check, if last scroll has happened at least 1s ago; if so: disable fast scroll, otherwise do nothing

**Comment by moving-bits** [comment]
> Some cosmetics: The position markers (bars) of slow and fast scroll seem to be not in sync, slow scroll bar is always a bit "higher" than the fast scroll bar. Are both of them based on Android libs or is one "self calculated"?

Not that I know of - should be both "Android original".

**Comment by moving-bits** [comment]
> > Some cosmetics: The position markers (bars) of slow and fast scroll seem to be not in sync, slow scroll bar is always a bit "higher" than the fast scroll bar. Are both of them based on Android libs or is one "self calculated"?
> 
> Not that I know of - should be both "Android original".

But at least in cache list view fast scroll acts on sections (groups of similar entries for the thumb), so if you have large and small groups, fast scroll bar gets out of sync as the regular scroll bar, as that one shows the position relative to the number of entries.

**Comment by moving-bits** [comment]
> This does not work over here. Sometimes fast scroll will not be disabled even for minutes ... but it's not deterministic ... strange.
> A scenario which "fails" fairly often is:

Thanks for digging deeper into this, and for the very helpful example - can reproduce it.
After some debugging I found out, that the `SCROLL_STATE_IDLE` notification gets skipped frequently, therefore not resetting the fast scroll mode.

I've implemented an alternative way, which seems to work pretty well in my first short tests. Will create a PR for it.
