### ISSUE TITLE
Use the new colorAccent in settings

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#8783]
Settings seems to ignore our new colorAccent:

![image](https://user-images.githubusercontent.com/3754370/89833017-99173600-db60-11ea-8733-6607f950a3f7.png)

**Comment by Lineflyer** [comment]
For me this does not seem to work with todays nightly.

**Comment by moving-bits** [comment]
I had developed and tested this with emulated API 29 device.
What version are you using?

**Comment by Lineflyer** [comment]
Tested on two devices both API 29.
I do still see blue accents in settings.

**Comment by moving-bits** [comment]
It should look like this:

![image](https://user-images.githubusercontent.com/3754370/90328605-e7cc3200-df9d-11ea-89e5-a4afd84bd204.png) ![image](https://user-images.githubusercontent.com/3754370/90328607-ef8bd680-df9d-11ea-8497-2a45c9e91bc7.png)

![image](https://user-images.githubusercontent.com/3754370/90328621-177b3a00-df9e-11ea-8c16-afa670dc80cb.png) ![image](https://user-images.githubusercontent.com/3754370/90328623-1f3ade80-df9e-11ea-9804-3d170aef8ced.png)

Seems like the internal attributes differ between the systems. I'll try something and create a PR for it.

**Comment by Lineflyer** [comment]
I have built a new nightly 2020.08.16NB1-2e91303 to test the newest change from @moving-bits 

On my Samsungs Galaxy S10, Android 10 it looks as follows:
When opening the settings main screen I do already see the old (blue) color in my phone header:
![Screenshot_20200816-220309_cgeo](https://user-images.githubusercontent.com/949669/90342980-e0903d00-e00c-11ea-9ac6-64d5e9547339.jpg)

When entering e.g. the map settings (same in others) it looks blue as well:
![Screenshot_20200816-220317_cgeo](https://user-images.githubusercontent.com/949669/90342986-f1d94980-e00c-11ea-90af-88a514f059fc.jpg)

Just now I recognized (not sure if it was already OK some days ago or only today), that the color picker has the new accents:
![Screenshot_20200816-220325_cgeo](https://user-images.githubusercontent.com/949669/90343000-07e70a00-e00d-11ea-9ed0-0c66e250f908.jpg)

**Comment by murggel** [comment]
I have the blue color-accent in the live-maps-menu, when the google-maps is active. With offline-maps the orange color accent is used (2020.11.22)

Google-Maps
<img src="https://user-images.githubusercontent.com/70113341/100018156-578f5b80-2ddc-11eb-9b9b-20a6e7596757.jpg"  width="200"> <img src="https://user-images.githubusercontent.com/70113341/100018669-19df0280-2ddd-11eb-87ef-6778313636b0.jpg"  width="200">

Offline-Map
<img src="https://user-images.githubusercontent.com/70113341/100018161-59591f00-2ddc-11eb-9b4f-1b930f19b850.jpg"  width="200"> <img src="https://user-images.githubusercontent.com/70113341/100018667-19466c00-2ddd-11eb-8e78-303e46220624.jpg"  width="200">

Should I open a new issue?

**Comment by moving-bits** [comment]
It's yet another subtle styling difference between the different Android settings... We should open a generalized issue for reworking the program's styling, as mentioned in https://github.com/cgeo/cgeo/pull/9422#issuecomment-732443741

**Comment by fm-sys** [comment]
There is already one, see #9373

**Comment by Lineflyer** [comment]
There is also another issue created by myself where I addressed the total theme dofference on GMapsV2 compared to other parts of the app. Need to look it up.

**Comment by fm-sys** [comment]
@murggel the bug you're pointing to is described here in detail: #7587

**Comment by moving-bits** [comment]
As this issue was originally about program settings:

@Lineflyer @murggel 
Can you cross-check using current beta or nightly, if the wrong colorAccent still happens _in c:geo settings_? Thx.
(For Google Maps and the quick settings popup within Google Maps there is a separate issue #9576.)

**Comment by murggel** [comment]
> @Lineflyer @murggel
> Can you cross-check using current beta or nightly, if the wrong colorAccent still happens _in c:geo settings_? Thx.

Still happens in current beta
![Screenshot_20201230-192904_cgeo](https://user-images.githubusercontent.com/70113341/103374111-01968d80-4ad7-11eb-97aa-e062a477dba9.jpg)

**Comment by moving-bits** [comment]
@murggel 
Thanks for cross-checking. Does this happen in dark theme only, or in both, dark and light, themes?

Do you happen to have an Android dev environment? If yes, can you try to find out what theme settings is using here (by debugging into it)? - My problem is that I cannot reproduce this error here, with neither emulated or physical test devices I have at hand.

**Comment by fm-sys** [comment]
I think this is a samsung specific problem. On my S5 mini the GM action bar was always blue in c:geo (don't know, if it's still like that). Anyway, no idea how to solve this issue...

**Comment by murggel** [comment]
> @murggel
> Thanks for cross-checking. Does this happen in dark theme only, or in both, dark and light, themes?

It happens only in dark mode.

> 
> Do you happen to have an Android dev environment? If yes, can you try to find out what theme settings is using here (by debugging into it)? 

Yes, I have local debugging environment, but no API-keys yet for Google Maps (I could get some, probably I need help with that, but this will take some days...)

But if @fm-sys is right (I also have a Samsung), that will probably lead to no success, I don't have a Samsung emulation.

**Comment by moving-bits** [comment]
Needs to be re-checked after merging #10049

**Comment by fm-sys** [comment]
@Lineflyer could you retest this issue at your Samsung device with the latest nightly?

**Comment by Lineflyer** [comment]
Yes, all orange now as it should be. Perfect!
