### ISSUE TITLE
[SAF] GPX export directory not matching

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#9775]
Testing the SAF nightlies:

- Have 2021.01.10 installed
- Set GPX export directory to `/storage/emulated/0/mygpx` 
- upgrade with 2021.01.10-NBSAF-ad614bc
- When asked on startup set the folder user defined to (my testcase) `/storage/emulated/0/cgeo/cgeo ud` (Selected to move existing)
- Export a GPX from a list
- GPX gets exported to `/storage/emulated/0/cgeo/gpx`

Two issues I see here:
1. The used directory is not correct (neither my previously selected user defined dir nor the new default)
2. Why after all is SAF able to export to  `/storage/emulated/0/cgeo/gpx` as the user did never gave such permission

**Comment by Lineflyer** [comment]
Just noticed, that also my user defined map directory can be written to (using map downloader) after updating to SAF, which is fine and smooth from users perspective, just I might not have understand why c.geo is able to do so when using SAF.

**Comment by Lineflyer** [comment]
```
--- System information ---
Device: Pixel 3a (sargo, google)
Android version: 11
Android build: RQ1A.201205.003
c:geo version: 2021.01.10-NBSAF-ad614bc
Google Play services: enabled - 20.47.14 (150400-349456378)
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: rotation vector
Hide caches: -
Hide waypoints: -
HW acceleration: enabled (default state)
System language: en_US / user-defined language: 
System date format: M/d/yy
Debug mode active: no
System internal c:geo dir: /data/user/0/cgeo.geocaching (33.6 GB free) internal
User storage c:geo dir: /storage/emulated/0/cgeo (33.6 GB free) external non-removable
Geocache data: /storage/emulated/0/Android/data/cgeo.geocaching/files/GeocacheData (33.6 GB free) external non-removable
Public Folders: #8
- BASE: …/Cgeo ud (User-defined)[…/Cgeo ud[DOCUMENT#0:p-content://com.android.externalstorage.documents/tree/primary%3ACgeo%20ud::], default: /storage/emulated/0/cgeo[FILE#0:p-file:///storage/emulated/0/cgeo::]] (Uri: content://com.android.externalstorage.documents/tree/primary%3ACgeo%20ud/document/primary%3ACgeo%20ud, Available:true, Fiies: 1, subdirs:5, free space: 33.6 GB, files on device: 12777472)
- OFFLINE_MAPS: /storage/emulated/0/offlinemap (User-defined)[/storage/emulated/0/offlinemap[FILE#0:p-file:///storage/emulated/0/offlinemap::], default: …/Cgeo ud/maps[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3ACgeo%20ud::/maps]] (Uri: file:///storage/emulated/0/offlinemap, Available:true, Fiies: 7, subdirs:0, free space: 33.6 GB, files on device: -1)
- OFFLINE_MAP_THEMES: /storage/emulated/0/offlinemap (User-defined)[/storage/emulated/0/offlinemap[FILE#0:p-file:///storage/emulated/0/offlinemap::], default: …/Cgeo ud/themes[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3ACgeo%20ud::/themes]] (Uri: file:///storage/emulated/0/offlinemap, Available:true, Fiies: 7, subdirs:0, free space: 33.6 GB, files on device: -1)
- LOGFILES: …/Cgeo ud/logfiles (Default)[…/Cgeo ud/logfiles[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3ACgeo%20ud::/logfiles], default: (same)] (Uri: content://com.android.externalstorage.documents/tree/primary%3ACgeo%20ud/document/primary%3ACgeo%20ud%2Flogfiles, Available:true, Fiies: 0, subdirs:0, free space: 33.6 GB, files on device: 12777472)
- GPX: /storage/emulated/0/cgeo/gpx (User-defined)[/storage/emulated/0/cgeo/gpx[FILE#0:p-file:///storage/emulated/0/cgeo/gpx::], default: …/Cgeo ud/gpx[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3ACgeo%20ud::/gpx]] (Uri: file:///storage/emulated/0/cgeo/gpx, Available:true, Fiies: 1, subdirs:0, free space: 33.6 GB, files on device: -1)
- BACKUP: …/Cgeo ud/backup (Default)[…/Cgeo ud/backup[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3ACgeo%20ud::/backup], default: (same)] (Uri: content://com.android.externalstorage.documents/tree/primary%3ACgeo%20ud/document/primary%3ACgeo%20ud%2Fbackup, Available:true, Fiies: 0, subdirs:1, free space: 33.6 GB, files on device: 12777472)
- FIELD_NOTES: …/Cgeo ud/field-notes (Default)[…/Cgeo ud/field-notes[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3ACgeo%20ud::/field-notes], default: (same)] (Uri: content://com.android.externalstorage.documents/tree/primary%3ACgeo%20ud/document/primary%3ACgeo%20ud%2Ffield-notes, Available:true, Fiies: 0, subdirs:0, free space: 33.6 GB, files on device: 12777472)
- TEST_FOLDER: /data/user/0/cgeo.geocaching/files/unittest (Default)[/data/user/0/cgeo.geocaching/files/unittest[FILE#1:p-file:///data/user/0/cgeo.geocaching/files::/unittest], default: (same)] (Uri: file:///data/user/0/cgeo.geocaching/files/unittest, Available:true, Fiies: 0, subdirs:0, free space: 33.6 GB, files on device: -1)
PersistedDocumentUris: #1
- TRACK: null
Persisted Uri Permissions: #1
- content://com.android.externalstorage.documents/tree/primary%3ACgeo%20ud (Jan 10, 10:58 PM):RW
Database: /data/user/0/cgeo.geocaching/databases/data (948.0 KB) on system internal storage
Last backup: Jan 10, 10:55 PM
Map render theme path: 
Live map mode: true
Global filter: display all caches
Sailfish OS detected: false
Fine location permission: granted
Write external storage permission: granted
Geocaching sites enabled:
   geocaching.com: Logged in (Login OK) / BASIC
Geocaching.com date format: MM/dd/yyyy
Installed c:geo plugins:  none
BRouter connection available: true
--- End of system information ---
```

**Comment by eddiemuc** [comment]
Thanks a lot for testing!

> The used directory is not correct (neither my previously selected user defined dir nor the new default)

I programmed saf such that it should take over user-defined directories from previous versions (pointing to file dirs of course) if no saf user directory is defined. This is for migration of course. I might have a bug there that this legacy value is taken over even if a new defined saf dir exists. Looks a bit like this because it seems to happen for all dirs where there is such a value acc to your system information.

Could you try to create a logfile and see where this ends up.

> Why after all is SAF able to export to /storage/emulated/0/cgeo/gpx as the user did never gave such permission

This is expected, not an error and necessary for smooth transition and migration. I simply left API level at 29 and legacy storage option set to true on the branch. We can only switch this up when complete c:geo is migrated (see open issues).

If you want to test the real thing (API30): maybe we could set up a separate branch for this? Be aware that there many things are not expected to work yet (themes, spoilers, ...) and migration will only work if you upgrade the device from android 10 to 11 with an already installed c:geo before!

**Comment by eddiemuc** [comment]
@Lineflyer I discovered a problem with file creation and missing mime types when selecting the directory. This leads to abortion of directory selection.

I assume this is the problem here. To confirm: can you maybe try and see whether your selection of a user-defined dir for GPX gets aborted by system (there should be a toast "Aborting dir selection" after you selected the user dir, and the dir value should be the same as before)? And you should have some sort of NPE in the log.

**Comment by eddiemuc** [comment]
Solved with https://github.com/cgeo/cgeo/commit/fb73c43c7b5a52b464f6f31ef5ab9bc029c67a6b

**Comment by eddiemuc** [comment]
Please retest before we close this issue

**Comment by Lineflyer** [comment]
> Could you try to create a logfile and see where this ends up.

The log file ends up in the new /ud cgeo/logfiles (according to my selected base dir). OK!

It seems only to affect the GPX export directory which was pre-SAF set to `/storage/emulated/0/mygpx` but ended up with `storage/emulated/0/cgeo/gpx` 

> To confirm: can you maybe try and see whether your selection of a user-defined dir for GPX gets aborted by system (there should be a toast "Aborting dir selection" after you selected the user dir, and the dir value should be the same as before)? And you should have some sort of NPE in the log.

Tested that (with the same build as informed above) and setting a new user-defines dir for GPX export (here `stprage/emulated/0/testgpx`)  works as expected. No failure toast. New dir is accepted. No NPE in log.

**Comment by Lineflyer** [comment]
> > Why after all is SAF able to export to /storage/emulated/0/cgeo/gpx as the user did never gave such permission
>
>This is expected, not an error and necessary for smooth transition and migration. I simply left API level at 29 and legacy storage option set to true on the branch. We can only switch this up when complete c:geo is migrated (see open issues).

Understood!
Can you explain why we should not directly remove the legacy flag? Is it regarding the open issue for map themes?

**Comment by Lineflyer** [comment]
Addition:
Tested another migration, this time from 2021.01.10 to the fresh SAF nightly 2021.01.11-NBSAF1-fb73c43 (including your latest commit). Problem is still there.

**Comment by eddiemuc** [comment]
> Can you explain why we should not directly remove the legacy flag? Is it regarding the open issue for map themes?

There is a couple of reasons imho:
* Map themes, offline log images and spoilers are not yet migrated
* I would argue to even go public with legacy flag turned on for a while so people can migrate in a "safe" environment (and we have a chance to react in case of failures - once we switch we can't even provide a bug fix release without the legacy mode turning off once and for all)
* It should be easier for nightly testing (in master) and beta testing phase for people

I would not turn on API level 30 before we are absolutely sure this works. And currently, it seems, this is yet not the case.

**Comment by eddiemuc** [comment]
> Addition:
> Tested another migration, this time from 2021.01.10 to the fresh SAF nightly 2021.01.11-NBSAF1-fb73c43 (including your latest commit). Problem is still there.

Ok that's not so good. Any exceptions or other findings in the log?

**Comment by Lineflyer** [comment]
> Ok that's not so good. Any exceptions or other findings in the log?

Need to check again tomorrow.

> I would argue to even go public with legacy flag turned on for a while so people can migrate in a "safe" environment (and we have a chance to react in case of failures - once we switch we can't even provide a bug fix release without the legacy mode turning off once and for all)

That sounds rather reasonable. So we have time to check and fix until Google might some day force us.

**Comment by Lineflyer** [comment]
Another strange finding which might be related:
Still using the above mentioned migration path with the problem described.
Now I went further to store/load an individual route:
- Exported route gets stored to `storage/emulated/0/cgeo/gpx`  Looks OK
- When trying to load an individual route the starting/initial folder what is shown is `/storage/emulated/0/mygpx` which is the I had selected as GPX export(!) directory before updating to the SAF version. 

Then I went further and tested GPX import from cache list menu:
- When trying to import a GPX the starting/initial folder what is shown is `/storage/emulated/0/mygpx` which is the I had selected as GPX export(!) directory before updating to the SAF version. 

Might there just be a mix-up while migrating?

Summary:
State before migration
GPX import: `storage/emulated/0/Download`
GPX export: `storage/emulated/0/mygpx`

State after migration:
GPX import: `storage/emulated/0/mygpx`
GPX export: `storage/emulated/0/cgeo/gpx`

-> `Download` for import seems to be lost
-> `mygpx` seems to be taken over for import instead export

**Comment by eddiemuc** [comment]
One update to the API thing: I forgot to mention "backup" which also needs to be migrated before setting to API30

**Comment by eddiemuc** [comment]
> -> Download for import seems to be lost
-> mygpx seems to be taken over for import instead export

This behaviour is expected. Since we decided to have only one user-selectable GPX dir in the future but have 2 of them currently (one for export, one for import) I had to make a decision which setting to take over in case both are set to an individual value (like in your scenario). I coded for now that "export" is preferred over "import". This can be discussed and adapted of course.

Apparently, however, your SAF-selected new dir is not used though which I have to investigate further, because this is of course a bug.

**Comment by eddiemuc** [comment]
Oh my, I am very sorry @Lineflyer I just read again your error description and it seems this was a misunderstanding on my side.

To confirm: in your setup after upgrading to the SAF-version you just set the base directory to a custom value, NOT the GPX directory -> correct?
In this scenario the system is actually programmed to take over the previously set custom value for GPX (just like you experienced it) until you explicitely also reset the GPX directory under Settings -> Offline Data. This a also of course to help migration such that the previously set GPX folder is not lost.

So the system works as expected wrt what I programmed. But of course we can discuss whether this is the right way. Would you prefer if the system just throws away previously set user-defined dir settings for GPX (export/import), offline maps or offline themes?

**Comment by Lineflyer** [comment]
> In this scenario the system is actually programmed to take over the previously set custom value for GPX (just like you experienced it) until you explicitely also reset the GPX directory under Settings -> Offline Data. This a also of course to help migration such that the previously set GPX folder is not lost.

I understand the approach and its reasonable, but this wasn't the case. Thats why I opened this issue.

Let me try to summarize again:
State before migration
GPX import dir setting: `storage/emulated/0/Download`
GPX export dir setting: `storage/emulated/0/mygpx`

State after migration:
Selected custom base folder: `/storage/emulated/0/cgeo ud/`
Folder showing up as default when trying GPX import: `storage/emulated/0/mygpx`
Folder which is used for GPX export: `storage/emulated/0/cgeo/gpx`

I would have expected without any manual changes:
- that the previous GPX import is now used as start folder for picking a file via SAF,(...Download)
- that my GPX exports still target the previously selected folder (...mygpx)

**Comment by eddiemuc** [comment]
@Lineflyer it is good you stayed persistend on this one. I found the problem: gpx legacy values werer not migrated directly. Had to turn my head around and understand the Settings migration concept..  PR #9788 should fix the problem.

However, one note: even after correct migration, when doing the sequence you did and the legacy gpx folder value is taken over, and you open a "gpx import" dialog, then this dialog will NOT open up in the expected folder. Reason is that the document picker intent of android apparently does not understand file uris, only content/document uris. I am afraid there is nothing we can do about. Once you start setting the folder on a content/document uri base (either by selecting it for the gpx dir directly or by setting a base uri and putting gpx dir to "default" (which means (base)/gpx) this will work of course.

**Comment by Lineflyer** [comment]
Thanks @eddiemuc and sorry for being so annoying. ;)  Hard life of testers :)

Will retest as time permits.

**Comment by Lineflyer** [comment]
Works as expected now with 2021.01.13-NBSAF-21722ac
